/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--bg)',
        'canvas-secondary': 'var(--bg-2)',
        surface: 'var(--surface)',
        'surface-raised': 'var(--surface-2)',
        'surface-sunken': 'var(--surface-3)',
        default: 'var(--border)',
        strong: 'var(--border-2)',
        primary: 'var(--text)',
        secondary: 'var(--text-2)',
        muted: 'var(--text-3)',
        action: 'var(--action)',
        'action-hover': 'var(--action-2)',
        'action-soft': 'var(--action-soft)',
        positive: 'var(--pos)',
        'positive-soft': 'var(--pos-soft)',
        negative: 'var(--neg)',
        'negative-soft': 'var(--neg-soft)',
        warning: 'var(--warn)',
        'warning-soft': 'var(--warn-soft)',
        information: 'var(--info)',
        'information-soft': 'var(--info-soft)',
        comparison: 'var(--cmp)',
        'comparison-soft': 'var(--cmp-soft)',
      },
      fontFamily: {
        sans: ['IBM Plex Sans', 'Arial Hebrew', 'Arial', 'system-ui', 'sans-serif'],
        mono: ['IBM Plex Mono', 'ui-monospace', 'SFMono-Regular', 'Consolas', 'monospace'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        flat: 'var(--shadow-flat)',
        raised: 'var(--shadow-raised)',
        overlay: 'var(--shadow-overlay)',
      },
      screens: {
        adaptive: '780px',
        compact: '1180px',
        wide: '1440px',
        mobileMax: { max: '779px' },
      },
    },
  },
  plugins: [],
};
