const en = {
  common: {
    appName: 'TradingLog', maximum: 'Maximum', allStatuses: 'All statuses', restOfApp: 'The rest of TradingLog',
    save: 'Save', saveChanges: 'Save changes', saving: 'Saving…', cancel: 'Cancel', delete: 'Delete', deleting: 'Deleting…', edit: 'Edit', close: 'Close', back: 'Back', retry: 'Try again', clearFilters: 'Clear filters', clearAll: 'Clear all', search: 'Search', actions: 'Actions', status: 'Status', type: 'Type', date: 'Date', from: 'From', to: 'To', account: 'Account', allAccounts: 'All accounts', symbol: 'Symbol', market: 'Market', direction: 'Direction', outcome: 'Outcome', strategy: 'Strategy', setup: 'Setup', timeframe: 'Timeframe', notes: 'Notes', description: 'Description', name: 'Name', title: 'Title', content: 'Content', optional: 'Optional', required: 'Required', yes: 'Yes', no: 'No', active: 'Active', inactive: 'Inactive', archived: 'Archived', paused: 'Paused', open: 'Open', closed: 'Closed', complete: 'Complete', incomplete: 'Incomplete', unavailable: 'Not available', noData: 'No data', loading: 'Loading…', today: 'Today', yesterday: 'Yesterday', previous: 'Previous', next: 'Next', more: 'More', all: 'All', none: 'None', count: 'Count', details: 'Details', filters: 'Filters', refresh: 'Refresh', export: 'Export', import: 'Import', create: 'Create', update: 'Update', view: 'View', result: 'Result', email: 'Email', password: 'Password', displayName: 'Display Name', company: 'Company', accountNumber: 'Account number', accountName: 'Account name', accountType: 'Account type', trades: 'Trades', entry: 'Entry', exit: 'Exit', entryPrice: 'Entry price', exitPrice: 'Exit price', quantity: 'Quantity', fees: 'Fees', netPnl: 'Net PnL', grossPnl: 'Gross PnL', winRate: 'Win rate', profitFactor: 'Profit factor', expectancy: 'Expectancy', averageR: 'Average R', risk: 'Risk', riskAmount: 'Risk amount', stopLoss: 'Stop loss', takeProfit: 'Take profit', duration: 'Duration', rMultiple: 'R multiple', long: 'Long', short: 'Short', breakeven: 'Breakeven', win: 'Win', loss: 'Loss', followed: 'Followed', broken: 'Broken', notApplicable: 'Not applicable', achieved: 'Achieved', missed: 'Missed', upcoming: 'Upcoming', inProgress: 'In progress', atLeast: 'At least', atMost: 'At most', timezone: 'Calendar timezone: {{timezone}}', pageControls: 'Page controls', unknown: 'Unknown', selected: 'Selected', language: 'Language', english: 'English', hebrew: 'עברית', new: 'New', record: 'Record', calendar: 'Calendar', timeline: 'Timeline', summary: 'Summary', total: 'Total', value: 'Value', target: 'Target', current: 'Current', progress: 'Progress', linkedTrades: 'Linked trades', tags: 'Tags', scope: 'Scope', rule: 'Rule', goal: 'Goal', journal: 'Journal', review: 'Review', period: 'Period', created: 'Created', updated: 'Updated', pageOf: 'Page {{page}} of {{pages}}', records: '{{count}} records', activeCount: '{{count}} active', allTime: 'All Time', thisWeek: 'This Week', lastWeek: 'Last Week', thisMonth: 'This Month', moreFilters: 'More filters', fewerFilters: 'Fewer filters', noChange: 'No change', gain: 'Gain', lossValue: 'Loss'
  },
  navigation: {
    trading: 'Trading', manage: 'Manage', insights: 'Insights', dashboard: 'Dashboard', trades: 'Trades', dailyReview: 'Daily Review', accounts: 'Accounts', import: 'Import', analytics: 'Analytics', journal: 'Journal & Reviews', rules: 'Rules & Adherence', goals: 'Goals', main: 'Main navigation', primary: 'Primary navigation', moreNavigation: 'More navigation', moreDestinations: 'More destinations', sidebar: 'Application sidebar', collapse: 'Collapse navigation', expand: 'Expand navigation'
  },
  routes: {
    dashboard: { title: 'Dashboard', description: 'Review trading performance across your current scope.' },
    trades: { title: 'Trades', description: 'Find, filter, export, and manage recorded trades.' },
    dailyReview: { title: 'Daily Review', description: 'Review the selected trading day, record what happened, and prepare for the next session.' },
    tradeDetail: { title: 'Trade details', description: 'Review the recorded trade context and outcome.' },
    accounts: { title: 'Accounts', description: 'Manage the accounts used to organize trading activity.' },
    import: { title: 'Import', description: 'Bring broker trade files into an existing account.' },
    analytics: { title: 'Analytics', description: 'Analyze trading performance across markets, direction, strategy, timing, and account scope.' },
    journal: { title: 'Journal & Reviews', description: 'Capture notes and structured reviews, then connect them to the trades they describe.' },
    rules: { title: 'Rules & Adherence', description: 'Define your trading rules, record what happened, and measure process consistency over time.' },
    goals: { title: 'Goals', description: 'Set measurable trading and process goals, then track progress from your real activity.' }
  },
  auth: {
    signInJournal: 'Sign in to your journal', createJournal: 'Create your trading journal', signIn: 'Sign In', signingIn: 'Signing in…', createAccount: 'Create Account', creatingAccount: 'Creating account…', noAccount: 'No account?', createOne: 'Create one', alreadyAccount: 'Already have an account?', passwordMin: 'Password must be at least 8 characters.', passwordLabel: 'Password * (min 8 characters)', emailLabel: 'Email *', loginFailed: 'Login failed.', signupFailed: 'Signup failed.', loggedOut: 'Logged out.'
  },
  shell: {
    breadcrumb: 'Breadcrumb', searchCommand: 'Search or run a command', searchCommands: 'Search commands', commandPlaceholder: 'Navigate or run an available action', availableCommands: 'Available commands', noCommands: 'No matching commands', commandHelp: 'Use Up and Down to move, Enter to open, and Escape to close.', goTo: 'Go to {{label}}', newJournal: 'New journal entry', newJournalDescription: 'Open the Journal & Reviews entry form', newRule: 'New Rule', newRuleDescription: 'Create a trading rule', recordCheck: 'Record Rule Check', recordCheckDescription: 'Record whether a trading rule was followed', newGoal: 'New Goal', newGoalDescription: 'Create a measurable goal', lightTheme: 'Use light theme', darkTheme: 'Use dark theme', logout: 'Log out', notifications: 'Notifications', dismissNotification: 'Dismiss notification', closeDialog: 'Close dialog', languageLabel: 'Choose application language'
  },
  status: {
    active: 'Active', inactive: 'Inactive', archived: 'Archived', paused: 'Paused', open: 'Open', closed: 'Closed', complete: 'Complete', incomplete: 'Incomplete', upcoming: 'Upcoming', in_progress: 'In progress', achieved: 'Achieved', missed: 'Missed', followed: 'Followed', broken: 'Broken', not_applicable: 'Not applicable', long: 'Long', short: 'Short', win: 'Win', loss: 'Loss', breakeven: 'Breakeven', funded: 'Funded', evaluation: 'Evaluation', demo: 'Demo', live: 'Live', trade: 'Trade', daily: 'Daily', general: 'General', note: 'Note', trade_review: 'Trade Review', daily_review: 'Daily Review', weekly_review: 'Weekly Review'
  },
  states: {
    noMatching: 'No matching results', nothingYet: 'Nothing here yet', somethingWrong: 'Something went wrong', stillAvailable: 'Still available: {{available}}'
  },
  validation: {
    required: '{{field}} is required.', invalidDate: 'Enter a valid date.', invalidNumber: 'Enter a valid number.', dateRange: 'End date cannot be before start date.', maxLength: '{{field}} must be {{max}} characters or fewer.', passwordMin: 'Password must be at least 8 characters.'
  },
  errors: {
    unknown: 'Something went wrong. Please try again.', network: 'The server could not be reached. Please try again.', unauthorized: 'Your session has expired. Please sign in again.', DAILY_REVIEW_DUPLICATE_ENTRIES: 'More than one Daily Review exists for this date. Resolve the duplicate Journal entries before continuing.', saveFailed: 'Changes could not be saved.', deleteFailed: 'The item could not be deleted.', loadFailed: 'The data could not be loaded.'
  },
  dashboard: { performance: 'Performance', recentTrades: 'Recent trades', noTrades: 'No trades in this period', noTradesDetail: 'Record a trade or change the selected period to see performance.', dailyPnl: 'Daily PnL', periodPnl: 'Period PnL', closedTrades: 'Closed trades', openTrades: 'Open trades', winners: 'Winners', losers: 'Losers', bestTrade: 'Best trade', worstTrade: 'Worst trade', equityCurve: 'Cumulative net PnL', calendar: 'Trading calendar', addTrade: 'Add Trade', today: 'Today', wtd: 'WTD', mtd: 'MTD', custom: 'Custom' },
  trades: { addTrade: 'Add Trade', editTrade: 'Edit trade', cancelEdit: 'Cancel edit', deleteTrade: 'Delete trade', tradeDeleted: 'Trade deleted.', tradeUpdated: 'Trade updated!', createFailed: 'Failed to create trade.', updateFailed: 'Update failed.', deleteFailed: 'Failed to delete trade.', deleteConfirm: 'Delete this trade permanently?', deleteConfirmShort: 'Delete this trade?', exportCsv: 'Export CSV', exportFailed: 'Export failed.', recordedCaption: 'Recorded trades with account, entry, result, status, and actions', noTrades: 'No trades found', noTradesDetail: 'No trades match the selected filters.', loading: 'Loading trades', details: 'Trade details', financialResult: 'Financial result', entryExit: 'Entry and exit', planOutcome: 'Plan versus outcome', context: 'Trading context', emotions: 'Emotions', attachments: 'Screenshot links', attachment: 'Attachment {{number}} · {{host}}', openAttachment: 'Open trade attachment {{number}} from {{host}} in a new tab', back: 'Back to trades', loadError: 'Trade details could not be loaded', unavailableRecord: 'The trade record is unavailable right now.', notFound: 'Trade not found', notFoundDetail: 'This trade record is unavailable or may have been removed.', openDetails: 'Open {{symbol}} trade details', sortBy: 'Sort by {{label}}{{status}}', currently: ', currently {{order}}', ascending: 'ascending', descending: 'descending', marketHelp: 'Market type for this trade.', exitHelp: 'Leave both exit fields empty for an open trade.', screenshotHelp: 'One URL per line.', screenshots: 'Screenshot links (optional)' },
  accounts: { newAccount: 'New Account', editAccount: 'Edit Account', deleteAccount: 'Delete Account', accountCreated: 'Account created!', accountUpdated: 'Account updated!', accountDeleted: 'Account deleted.', loadFailed: 'Failed to load accounts.', saveFailed: 'Failed to save account.', deleteFailed: 'Failed to delete account.', noAccounts: 'No accounts yet', noAccountsDetail: 'Create an account before recording or importing trades.', hasTrades: 'This account has {{count}} trade(s). You must reassign or delete those trades before deleting this account.', permanentDelete: 'Permanently delete {{account}}? This cannot be undone.', tradingAccounts: 'Trading Accounts', tradesCount: 'Trades count' },
  analytics: { summary: 'Performance summary', netPnl: 'Net PnL', winRate: 'Win rate', profitFactor: 'Profit factor', expectancy: 'Expectancy', averageWin: 'Average win', averageLoss: 'Average loss', closedTrades: 'Closed trades', cumulative: 'Cumulative net PnL', dollarDistribution: 'Dollar PnL distribution', rDistribution: 'R distribution', breakdown: 'Performance breakdown', calendar: 'Trading calendar', noData: 'No analytics data for this scope', noDataDetail: 'Record closed trades or adjust the selected scope.', timezoneHelp: 'Calendar dates use {{timezone}}.', bySymbol: 'By symbol', byMarket: 'By market', byDirection: 'By direction', byStrategy: 'By strategy', bySetup: 'By setup', byTimeframe: 'By timeframe', byAccount: 'By account', byCompany: 'By company', byWeekday: 'By weekday' },
  journal: { newEntry: 'New Journal Entry', editEntry: 'Edit Journal Entry', deleteEntry: 'Delete entry', entrySaved: 'Journal entry saved.', entryDeleted: 'Journal entry deleted.', saveFailed: 'Journal entry could not be saved.', deleteFailed: 'Journal entry could not be deleted.', deleteConfirm: 'Delete this Journal entry?', noEntries: 'No Journal entries yet', noEntriesDetail: 'Create a note or review to begin your Journal timeline.', filteredEmpty: 'No Journal entries match the current filters', entryType: 'Entry type', entryDate: 'Entry date', completeOnly: 'Complete only', incompleteOnly: 'Incomplete only', allCompletion: 'All completion states', searchPlaceholder: 'Search title, content, or tags', tagsHelp: 'Separate tags with commas.', linkedTradesHelp: 'Choose any trades described by this entry.', journalEntry: 'Journal Entry' },
  rules: { newRule: 'New Rule', editRule: 'Edit Rule', recordCheck: 'Record Rule Check', editCheck: 'Edit Rule Check', adherence: 'Rule adherence', activeRules: 'Active rules', inactiveRules: 'Inactive rules', history: 'Check history', noRules: 'No trading rules yet', noRulesDetail: 'Create a rule to begin measuring adherence.', noChecks: 'No rule checks in this period', followed: 'Followed', broken: 'Broken', notApplicable: 'Not applicable', eligibleChecks: 'Eligible checks', ruleCreated: 'Rule created.', ruleUpdated: 'Rule updated.', ruleDeleted: 'Rule deleted.', checkSaved: 'Rule check saved.', deleteConfirm: 'Delete this rule?', hasChecks: 'Rules with checks cannot be deleted.', ruleName: 'Rule name', checkDate: 'Check date', linkedTrade: 'Linked trade', linkedJournal: 'Linked Journal entry', noEligible: 'No eligible checks' },
  goals: { newGoal: 'New Goal', editGoal: 'Edit Goal', deleteGoal: 'Delete goal', goalCreated: 'Goal created.', goalUpdated: 'Goal updated.', goalDeleted: 'Goal deleted.', saveFailed: 'Goal could not be saved.', deleteFailed: 'Goal could not be deleted.', deleteConfirm: 'Delete this goal? Source records will remain unchanged.', deleteNamedConfirm: 'Delete “{{name}}”? This removes only the goal definition.', noGoals: 'No goals yet', noGoalsDetail: 'Create a measurable goal to begin tracking progress from your trading activity.', filteredEmpty: 'No goals match the current filters', clearFilterDetail: 'Clear the current filters to return to all goals.', metric: 'Metric', targetValue: 'Target value', startDate: 'Start date', endDate: 'End date', comparison: 'Comparison', storedStatus: 'Stored status', derivedState: 'Current state', currentValue: 'Current value', difference: 'Difference to target', pause: 'Pause', resume: 'Resume', archive: 'Archive', restore: 'Restore', withinLimit: 'Within limit', overLimit: 'Over limit', overLimitBy: 'Over limit by', remainingAllowance: 'Remaining allowance', targetAchieved: 'Target achieved', maxAllowed: 'Maximum allowed', unavailable: 'Current value is unavailable.', progressLabel: '{{name}}: current {{current}}, target {{target}}, {{percent}}%, {{state}}', progressUnavailable: 'Progress percentage is not meaningful for this target value.', no_closed_trades: 'No closed trades in this goal period.', no_r_data: 'No trades with R data in this goal period.', no_eligible_rule_checks: 'No eligible rule checks in this goal period.', source_unavailable: 'This source could not be calculated right now.', summary: 'Goals summary', loadingSummary: 'Loading Goals summary', loadingMetric: 'Loading goal metric', filters: 'Goal filters', search: 'Search goals', statusFilter: 'Goal status', metricFilter: 'Goal metric', allMetrics: 'All metrics', refreshing: 'Refreshing Goals…', refreshFailed: 'Goals could not be refreshed', staleVisible: 'The last available Goals remain visible.', availableActions: 'Filters and existing goal actions', loadFailed: 'Goals could not be loaded', loadFailedDetail: 'Goal definitions and progress calculations are unavailable right now.', activeUpcoming: 'Active and upcoming', outcomes: 'Outcomes', pausedArchived: 'Paused and archived' },
  importPage: { title: 'Import trades', selectFile: 'Select file', mapping: 'Map columns', preview: 'Preview', results: 'Import results', chooseAccount: 'Choose account', chooseFile: 'Choose a CSV file', upload: 'Upload and preview', importing: 'Importing…', importTrades: 'Import trades', cancelImport: 'Cancel import', file: 'File', rows: 'Rows', validRows: 'Valid rows', invalidRows: 'Invalid rows', duplicates: 'Duplicates', errors: 'Errors', complete: 'Import complete', failed: 'Import failed', requiredColumns: 'Required columns', optionalColumns: 'Optional columns' },
  dailyReview: { sessionNotes: 'Session notes', wentWell: 'What went well', improve: 'What should improve', nextPlan: 'Next-session plan', emotions: 'Emotions', mistakes: 'Mistakes', saveReview: 'Save Daily Review', saved: 'Daily Review saved.', saveFailed: 'Daily Review could not be saved.', noReview: 'No Daily Review saved yet', noReviewDetail: 'Record what happened and prepare for the next session.', daySummary: 'Day summary', tradesTaken: 'Trades taken', rulesChecks: 'Rules and checks', reviewSection: 'Review notes', recordCheck: 'Record Check', noRules: 'No active rules', noChecks: 'No checks recorded for this date', noTrades: 'No trades entered on this date', completion: 'Mark this review complete', previousDay: 'Previous day', nextDay: 'Next day', openToday: 'Open today', invalidDate: 'This Daily Review date is invalid.', invalidDateDetail: 'Use a real YYYY-MM-DD calendar date.', calendarTimezone: 'Calendar timezone: {{timezone}}', closedTrades: 'Closed trades', openTrades: 'Open trades', winners: 'Winners', losers: 'Losers', bestTrade: 'Best trade', worstTrade: 'Worst trade', feeTotal: 'Fees', adherence: 'Rule adherence', checkCount: '{{count}} checks', latest: 'Latest: {{outcome}}', customEmotion: 'Add a custom emotion', customMistake: 'Add a custom mistake', add: 'Add', maxItems: 'Choose up to {{max}} items.', contentRequired: 'Session notes are required.' }
};

Object.assign(en.common, { any: 'Any' });
Object.assign(en.analytics, {
  loadingScope: 'Loading Analytics scope summary', scopeFailed: 'Scope summary could not be loaded', closedUnavailable: 'The closed-trade count is unavailable.', scopeAvailable: 'Scope controls and any successful analysis widgets', scopeSummary: 'Analytics scope summary', dateRange: 'Date range', accountScope: 'Account scope', calendarTimezone: 'Calendar timezone', allCompanies: 'All companies', period: 'Analytics period', customDates: 'Custom Analytics dates', accountsLoadFailed: 'Account options could not be loaded. All-account Analytics remains available.', retryAccounts: 'Retry accounts', loadFailed: 'Analytics could not be loaded', loadFailedDetail: 'The scope summary, dimension analysis, and R distribution all failed.', controlsAvailable: 'Account and period controls', noClosedScope: 'No closed trades in this scope', noClosedScopeDetail: 'Choose another account or date range to analyze recorded outcomes.', weekday: 'Weekday', breakdownDetails: 'Breakdown details for the selected dimension', group: 'Group', viewDetails: 'View breakdown details', dimensionAnalysis: 'Dimension analysis', dimensionDescription: 'Closed-trade net PnL and outcomes grouped by {{dimension}}.', dimensionControl: 'Analyze performance by dimension', dimensionFailed: 'Dimension analysis could not be loaded', dimensionUnavailable: 'The {{dimension}} breakdown is unavailable.', dimensionAvailable: 'Scope controls and R-multiple distribution', noDimension: 'No {{dimension}} breakdown', noDimensionDetail: 'No closed trades in this scope can be grouped for this dimension.', closedTradeSummary: '{{count}} closed trade · {{rate}} win rate', closedTradeSummary_other: '{{count}} closed trades · {{rate}} win rate', tradeCount: '{{count}} trade', tradeCount_other: '{{count}} trades', loadingR: 'Loading R-multiple distribution', rFailed: 'R-multiple distribution could not be loaded', rFailedDetail: 'Stored R-multiple buckets are unavailable for this scope.', rAvailable: 'Scope controls and dimension analysis', rUnavailable: 'R-multiple data is unavailable', rUnavailableDetail: 'Closed trades exist in this scope, but none has a stored R multiple. Missing risk data is not treated as 0R.', rDescription: 'Stored results for {{count}} closed trades, measured against planned risk.'
});
Object.assign(en.importPage, {
  selectUpload: 'Select & Upload', done: 'Done', progress: 'Import progress', noRows: 'No rows to preview.', previewTable: 'Imported trade preview', broker: 'Broker', csvFile: 'CSV File', parsing: 'Parsing…', selectBrokerError: 'Please select a broker.', selectFileError: 'Please choose a CSV file.', selectAccountError: 'Please select an account for these trades.', parseFailed: 'Failed to parse CSV.', totalRows: 'Total rows in file', uniqueRows: 'Unique in file', inFileDuplicates: 'In-file duplicates', previewCount: 'Preview (first {{shown}} of {{total}} unique rows)', assignAccount: 'Assign to Account *', assignAccountHelp: 'All imported trades will be assigned to this account.', importCount: 'Import {{count}} trade', importCount_other: 'Import {{count}} trades', startOver: 'Start Over', importedCount: 'Trades imported', existingCount: 'Already existed', viewTrades: 'View Trades', importMore: 'Import More'
});
Object.assign(en.rules, {
  overallAdherence: 'Overall adherence', summary: 'Adherence summary', notApplicableDetail: 'All checks in this period are not applicable, so they are excluded from the adherence denominator.', recordToMeasure: 'Record what happened to begin measuring adherence.', reactivateHelp: 'Reactivate this rule before recording a new check.', noLinkedContext: 'No linked context', overview: 'Overview', detailsUnavailable: 'Rule details are unavailable. Retry the rules list before editing.', period: 'Rules period', customDates: 'Custom Rules dates', view: 'Rules view', invalidRange: 'Date range is invalid', managementForms: 'Rules management and forms', perRule: 'Per-rule adherence', recentChecks: 'Recent checks', management: 'Rules management', search: 'Search rules', statusFilter: 'Rule status', scopeFilter: 'Rule scope', allScopes: 'All scopes', tabRules: 'Rules', createRule: 'Create rule', saveRule: 'Save rule', recordCheckSubmit: 'Record check', saveCheck: 'Save check', checkDeleted: 'Rule check deleted.'
});
Object.assign(en.rules, { recordCheck: 'Record Check', history: 'Check History', ruleCreated: 'Trading rule created.', ruleUpdated: 'Trading rule updated.', checkSaved: 'Rule check recorded.', hasChecks: 'This rule has historical checks. Deactivate it instead.' });
Object.assign(en.rules, { recordCheckDialog: 'Record Rule Check' });
Object.assign(en.accounts, { newAccount: 'New account' });
Object.assign(en.analytics, { cumulative: 'Cumulative realized PnL', rDistribution: 'R-multiple distribution' });
Object.assign(en.dailyReview, { noTrades: 'No trades on this date', invalidDate: 'Invalid Daily Review date', completion: 'Mark this Daily Review complete', customEmotion: 'Custom emotions', customMistake: 'Custom mistakes' });
Object.assign(en.accounts, { newAccountDialog: 'New Account' });
Object.assign(en.dashboard, { periodPnl: 'Period net PnL', noTrades: 'No closed trades in this period', loadFailed: 'Dashboard analytics could not be loaded', loadFailedDetail: 'The analytics requests failed. The independently loaded calendar may still be available.' });
Object.assign(en.analytics, { expectancyDescription: 'Average net PnL per closed trade' });
Object.assign(en.goals, { newGoalDialog: 'New goal', editGoalDialog: 'Edit goal', createGoal: 'Create goal', saveGoal: 'Save goal', targetRequired: 'Enter a target value.', wholeCount: 'Count targets must be whole numbers.', deleteFailed: 'Goal could not be deleted. It remains available.' });
Object.assign(en.journal, { newEntry: 'New Entry', newEntryDialog: 'New journal entry', editEntryDialog: 'Edit journal entry', createEntry: 'Create entry', entrySaved: 'Journal entry created.', noEntries: 'No journal entries yet', filteredEmpty: 'No entries match the current filters', noEntriesMonth: 'No journal entries this month' });
Object.assign(en.trades, { addTrade: 'Add trade', noTrades: 'No trades recorded yet', filteredEmpty: 'No trades match the current filters', loadFailed: 'Trades could not be loaded', filters: 'Trade filters', loadingDetails: 'Loading trade details' });
Object.assign(en.dashboard, { addTrade: 'Add Trade' });
Object.assign(en.trades, { entryTime: 'Entry time', exitTime: 'Exit time', outcomeR: 'Outcome R' });
Object.assign(en.dashboard, { loadingMetrics: 'Loading Dashboard metrics', period: 'Dashboard period', customDates: 'Custom Dashboard dates' });
Object.assign(en.journal, { timeline: 'Journal timeline', calendarHelp: 'Weeks begin on Sunday. Select a day to review its entries.', previousMonth: 'Previous month', nextMonth: 'Next month', noEntriesMonth: 'No Journal entries this month' });
Object.assign(en.analytics, {
  breakdownDescription: 'Closed-trade net PnL grouped by a supported production dimension.', loadingEquity: 'Loading cumulative realized PnL chart', equityFailed: 'Cumulative PnL could not be loaded', equityFailedDetail: 'The closed-trade running total is unavailable.', dashboardAvailable: 'Dashboard controls and any other successful widgets', noEquity: 'No realized PnL to chart', noEquityDetail: 'There are no closed trades in the selected scope for this chart.', cumulativeDescription: 'Running total of closed-trade net PnL for the selected scope.', loadingDistribution: 'Loading PnL distribution', distributionFailed: 'PnL distribution could not be loaded', distributionFailedDetail: 'Dollar-PnL buckets are unavailable.', noDistribution: 'No PnL distribution yet', noDistributionDetail: 'Closed trades are needed to populate dollar-PnL buckets.', distributionDescription: 'Closed trades grouped by their net profit or loss in US dollars.', loadingCalendar: 'Loading trading calendar', calendarFailed: 'Trading calendar could not be loaded', calendarFailedDetail: 'Daily realized PnL is unavailable for this month.', dailyRealized: 'Daily realized PnL', calendarDescription: 'Closed-trade net PnL by entry date; weeks begin on Sunday.', noCalendarTrades: 'No closed trades were recorded in this calendar month.', tradingDays: '{{count}} trading day in {{year}}.', tradingDays_other: '{{count}} trading days in {{year}}.', weekdays: { sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat' }
});

Object.assign(en.goals, { goalName: 'Goal name' });
Object.assign(en.journal, { noEntriesMonth: 'No journal entries this month' });

Object.assign(en.journal, {
  loadingTimeline: 'Loading journal timeline', loadingEntry: 'Loading journal entry', loadingTitle: 'Loading journal title', loadingContent: 'Loading journal content',
  controls: 'Journal controls', view: 'Journal view', search: 'Search journal entries', completionStatus: 'Completion status', fromDate: 'From date', toDate: 'To date',
  refreshFailed: 'Journal entries could not be refreshed', lastTimelineVisible: 'The last available timeline remains visible.', filtersCalendarForm: 'Filters, calendar, and entry form',
  entryCount: '{{count}} entry', entryCount_other: '{{count}} entries', refreshingTimeline: 'Refreshing timeline…', invalidRange: 'Date range is invalid', invalidRangeDetail: 'Choose an end date on or after the start date.', entriesFiltersUnchanged: 'Your existing entries and filters remain unchanged', loadFailed: 'Journal entries could not be loaded', loadFailedDetail: 'The timeline request failed.', calendarAndForm: 'Calendar and entry form',
  deleteNamedConfirm: 'Delete “{{title}}”?', loadingCalendar: 'Loading journal calendar', calendarLoadFailed: 'Journal calendar could not be loaded', monthCountsUnavailable: 'Month-level entry counts are unavailable.', timelineAndForm: 'Timeline and journal entry form', calendarRefreshFailed: 'Journal calendar could not be refreshed', lastMonthVisible: 'The last available month remains visible.', refreshingCalendar: 'Refreshing calendar…', entriesForMonth: 'Journal entries for {{month}}', daySummaryLabel: '{{date}}, {{total}} entries, {{complete}} complete, {{incomplete}} incomplete', selectedDay: 'Selected day', selectDay: 'Select a calendar day', selectDayDetail: 'Choose a day to see its real journal entries.', loadingSelectedDay: 'Loading selected day entries', selectedDayLoadFailed: 'Selected day could not be loaded', selectedDayUnavailable: 'Entries for this day are unavailable.', monthNavigation: 'Month counts and navigation', noEntriesDay: 'No journal entries on this day', noEntriesDayDetail: 'The selected calendar date has no saved entries.', selectedDayRefreshFailed: 'Selected day could not be refreshed', lastEntriesVisible: 'The last available entries remain visible.',
  chooseEntryType: 'Choose an entry type.', chooseDate: 'Choose a journal date.', enterTitle: 'Enter a title.', enterContent: 'Enter journal content.', tagsPlaceholder: 'process, patience', searchTrades: 'Search trades by symbol', searchBySymbol: 'Search by symbol', selectedTradesCount: '{{count}} of {{max}} selected', loadingRecentTrades: 'Loading recent trades…', tradesLoadFailed: 'Trades could not be loaded. Existing selections are preserved.', noTradeMatches: 'No owned trades match this symbol search.', availableTrades: 'Available trades'
});

Object.assign(en.rules, {
  loadingSummary: 'Loading adherence summary', loadingMetric: 'Loading adherence metric', lastCheck: 'Last check', ruleAdherenceLabel: '{{name}} adherence', historyPages: 'Check history pages', deleteNamedConfirm: 'Delete “{{name}}”? Rules with historical checks cannot be deleted.', deleteCheckConfirm: 'Delete the {{outcome}} check for “{{name}}”?',
  fullLoadFailed: 'Rules & Adherence could not be loaded', fullLoadFailedDetail: 'Rules, adherence, and check history requests failed.', periodAndForms: 'Period controls and forms', summaryLoadFailed: 'Adherence summary could not be loaded', rulesHistoryAvailable: 'Rules and check history remain available.', managementHistory: 'Rules management and history', refreshFailed: 'Adherence could not be refreshed', lastResultsVisible: 'The last available results remain visible.', rulesAndHistory: 'Rules and history', recentLoadFailed: 'Recent checks could not be loaded', adherenceRulesAvailable: 'Adherence and rules remain available.', adherenceManagement: 'Adherence and rule management', rulesRefreshFailed: 'Rules could not be refreshed', lastRulesVisible: 'The last available rules remain visible.', editingChecksAvailable: 'Editing and check recording', loadingRules: 'Loading rules', rulesLoadFailed: 'Rules could not be loaded', rulesRequestFailed: 'The rules request failed.', adherenceHistory: 'Adherence and check history', filteredEmpty: 'No rules match the current filters', clearRuleFiltersDetail: 'Clear the current filters to return to all rules.', historicalChecks: '{{count}} historical check', historicalChecks_other: '{{count}} historical checks', deactivate: 'Deactivate', reactivate: 'Reactivate', historyRule: 'History rule', allRules: 'All rules', historyOutcome: 'History outcome', allOutcomes: 'All outcomes', historyRefreshFailed: 'Check history could not be refreshed', lastChecksVisible: 'The last available checks remain visible.', adherenceAndRules: 'Adherence and rules', loadingHistory: 'Loading check history', historyLoadFailed: 'Check history could not be loaded', historyLoadFailedDetail: 'The history request failed. Adherence and rules remain available.', clearCheckFiltersDetail: 'Clear the current filters to return to all checks in this period.',
  chooseRule: 'Choose a rule.', chooseCheckDate: 'Choose a check date.', chooseOutcome: 'Choose an outcome.', scopeHelp: { trade: 'Trade rules commonly link to a trade.', daily: 'Daily rules commonly link to a daily review.', general: 'General rules may be recorded without a link.' }, noLinkedTrade: 'No linked trade', tradesLoadFailed: 'Trades could not be loaded. The current selection is preserved.', searchJournal: 'Search Journal entries', searchJournalPlaceholder: 'Search title or content', availableJournal: 'Available Journal entries', noLinkedJournal: 'No linked Journal entry', journalLoadFailed: 'Journal entries could not be loaded. The current selection is preserved.'
});

Object.assign(en.dailyReview, { metricsLoadFailed: 'Day metrics could not be loaded', tradesRulesReviewAvailable: 'Trades, Rules, and review notes remain available.', tradesLoadFailed: 'Trades could not be loaded', rulesReviewAvailable: 'You can still record Rules and save the review.', noStrategyContext: 'No strategy context', realizedUnavailable: 'Realized PnL —', rulesLoadFailed: 'Rules could not be loaded', tradesReviewAvailable: 'Trades and your Daily Review remain available.', reviewLoadFailed: 'Daily Review could not be loaded', reviewLoadFailedDetail: 'Day metrics, trades, and Rules remain available. Retry before editing to avoid overwriting unknown content.' });
Object.assign(en.analytics, { winsLosses: 'W / L', refreshingDimension: 'Refreshing dimension analysis…', breakdownBy: 'Break down performance by', breakdownLoadFailed: 'Performance breakdown could not be loaded', groupingUnavailable: 'The {{dimension}} grouping is unavailable.', otherWidgetsAvailable: 'Other successful Dashboard widgets and breakdown controls', refreshingR: 'Refreshing R distribution…', rBucketCounts: 'R-multiple bucket counts', refreshingCalendar: 'Refreshing calendar…', tradeSummary: '{{count}} trades · Win rate: {{rate}}', loadingBreakdown: 'Loading performance breakdown', noBreakdown: 'No {{dimension}} breakdown yet', noBreakdownDetail: 'No closed trades in the selected scope can be grouped for this view.', topGroups: 'Top {{shown}} of {{total}} groups by net PnL.', groupsInScope: '{{count}} group in scope.', groupsInScope_other: '{{count}} groups in scope.', netPnlChartLabel: 'Net PnL chart for {{count}} {{dimension}} groups.' });
Object.assign(en.journal, { netPnlUnavailable: 'Net PnL unavailable', editNamed: 'Edit {{title}}', deleteNamed: 'Delete {{title}}', pagination: 'Journal timeline pagination' });
Object.assign(en.trades, { activeFilters: 'Active filters', loadingHeader: 'Loading table header', loadingRow: 'Loading trade row', filter: { from: 'From', to: 'To', accountId: 'Account', symbol: 'Symbol', market: 'Market', direction: 'Direction', status: 'Status', outcome: 'Outcome', strategy: 'Strategy', timeframe: 'Timeframe' } });
Object.assign(en.trades, { notesPlaceholder: 'Strong volume on breakout…' });
Object.assign(en.accounts, { numberPlaceholder: 'e.g. 12345678', namePlaceholder: 'e.g. Main Funded' });
Object.assign(en.analytics, { increased: 'increased', decreased: 'decreased', unchanged: 'was unchanged', equityChartLabel: 'Cumulative realized PnL {{direction}} over {{count}} plotted days and ends at {{value}}.', dailyNetPnl: 'Daily net PnL' });
Object.assign(en.goals, { metricHelp: { closed_trades: 'Number of closed trades.', win_rate: 'Existing production win-rate definition.', average_r: 'Average stored R where available.', rule_adherence: 'Followed divided by followed plus broken.', journal_entries: 'Number of Journal entries.', broken_rule_checks: 'Maximum allowed broken checks.' } });
Object.assign(en.rules, { newRuleDialog: 'New trading rule', editRuleDialog: 'Edit trading rule', recordCheckFormDialog: 'Record rule check', editCheckDialog: 'Edit rule check' });
Object.assign(en.journal, { daySummaryLabel: '{{date}}, {{total}} entry, {{complete}} complete, {{incomplete}} incomplete', daySummaryLabel_other: '{{date}}, {{total}} entries, {{complete}} complete, {{incomplete}} incomplete' });
Object.assign(en.analytics, { netPnlChartLabel: 'Net PnL for {{count}} {{dimension}} group.', netPnlChartLabel_other: 'Net PnL for {{count}} {{dimension}} groups.', dimensionNames: { strategy: 'strategy', symbol: 'symbol', timeframe: 'timeframe', direction: 'direction', account: 'account', company: 'company', market: 'market', weekday: 'weekday', setup: 'setup' } });
Object.assign(en.analytics, { dimensionChartLabel: 'Net PnL chart for {{count}} {{dimension}} group.', dimensionChartLabel_other: 'Net PnL chart for {{count}} {{dimension}} groups.' });
Object.assign(en.common, { working: 'Working' });
Object.assign(en.analytics, { loadingDimension: 'Loading dimension analysis' });
Object.assign(en.dailyReview, { loadingMetric: 'Loading day metric', loadingReview: 'Loading Daily Review' });
Object.assign(en.dailyReview, { emotionSuggestions: ['Focused', 'Patient', 'Confident', 'Calm', 'Anxious', 'Frustrated', 'FOMO'], mistakeSuggestions: ['Overtrading', 'Chased entry', 'Moved stop', 'Oversized risk', 'Revenge trade', 'Early exit'] });
Object.assign(en.rules, { loadingPerRule: 'Loading per-rule adherence', loadingRecent: 'Loading recent checks' });
Object.assign(en.trades, { loadingCard: 'Loading trade card' });
Object.assign(en.status, { stocks: 'Stocks', crypto: 'Crypto', futures: 'Futures', forex: 'Forex' });
Object.assign(en.goals.metricHelp, { net_pnl: 'Closed-trade net PnL in the goal period.' });
Object.assign(en.errors, { ACCOUNT_NOT_FOUND: 'The account was not found.', EMAIL_IN_USE: 'An account with this email already exists.', GOAL_NOT_FOUND: 'The goal was not found.', INVALID_CREDENTIALS: 'Invalid email or password.', INVALID_FILE: 'The selected file is invalid.', INVALID_JOURNAL_LINK: 'The linked Journal entry is unavailable.', INVALID_REFRESH_TOKEN: 'Your session has expired. Please sign in again.', INVALID_RULE_LINK: 'The linked rule is unavailable.', INVALID_TRADE_LINK: 'The linked trade is unavailable.', JOURNAL_ENTRY_NOT_FOUND: 'The Journal entry was not found.', NO_REFRESH_TOKEN: 'Your session has expired. Please sign in again.', RULE_CHECK_NOT_FOUND: 'The rule check was not found.', RULE_HAS_CHECKS: 'Rules with historical checks cannot be deleted.', RULE_NOT_FOUND: 'The rule was not found.', SESSION_EXPIRED: 'Your session has expired. Please sign in again.', TRADE_NOT_FOUND: 'The trade was not found.', USER_NOT_FOUND: 'The user was not found.', VALIDATION_ERROR: 'Please correct the highlighted values.' });
Object.assign(en.auth, { namePlaceholder: 'Alex' });
Object.assign(en.validation, { numberRange: 'Enter a value from {{min}} to {{max}}.' });
Object.assign(en.goals, { targetWithUnit: 'Target ({{unit}})', countUnit: 'count', nameRequired: 'Enter a goal name.', endDateOrder: 'End date must not precede start date.' });
Object.assign(en.rules, { nameRequired: 'Enter a rule name.' });
Object.assign(en.routes, {
  tradeNew: { title: 'New Trade', description: 'Record a new trade with the context needed for an accurate review.' },
  tradeEdit: { title: 'Edit Trade', description: 'Update the recorded outcome and review context for this trade.' },
});
Object.assign(en.trades, {
  newTrade: 'New Trade', newTradeDescription: 'Open the complete Trade Editor', quickAdd: 'Quick Add', quickAddDescription: 'Record the essential trade details quickly',
  tradeCreated: 'Trade created.', saveTrade: 'Save Trade', saveChanges: 'Save changes', saveAndAddAnother: 'Save and add another', openFullForm: 'Open full form',
  openFullFormConfirm: 'Open the full form and discard the values entered in Quick Add?', discardQuickAddConfirm: 'Discard the values entered in Quick Add?',
  discardConfirm: 'You have unsaved changes. Discard them?', presentationMode: 'Form detail', presentationModeHelp: 'Simple and Advanced use the same trade record.',
  simple: 'Simple', advanced: 'Advanced', selectAccount: 'Select an active account…', symbolPlaceholder: 'AAPL', strategyPlaceholder: 'Opening Range Breakout', setupPlaceholder: 'Breakout',
  statusHelp: 'Open trades have no exit. Closed trades require both exit fields.', closedTradeHelp: 'The server calculates realized results from the saved trade.',
  timezoneHelp: 'Times use {{timezone}}.', entryDatetime: 'Entry date and time', exitDatetime: 'Exit date and time', identityLockedHelp: 'Trade identity and entry fields are preserved by the current API; outcome and review fields remain editable.',
  emotionPre: 'Emotion before entry', emotionDuring: 'Emotion during trade', emotionPost: 'Emotion after exit', editorLoading: 'Loading Trade Editor', loadingAccounts: 'Loading accounts…', refreshingEditor: 'Refreshing Trade Editor data…',
  accountsLoadFailed: 'Accounts could not be loaded', accountsLoadFailedDetail: 'A real owned account is required before a trade can be saved.', openAccounts: 'Open Accounts',
  invalidTrade: 'Invalid trade address', invalidTradeDetail: 'The edit address does not contain a valid trade identifier.', backToTrade: 'Back to trade', backToTrades: 'Back to trades',
  sections: {
    identity: 'Trade details', identityHelp: 'Choose the owned account and identify the trade.', entry: 'Entry details', exit: 'Exit details', risk: 'Risk management',
    riskHelp: 'These inputs support the server’s existing risk and R calculations.', context: 'Strategy and context', notes: 'Notes and emotions',
  },
  validation: {
    accountRequired: 'Select an account.', symbolRequired: 'Enter a symbol.', marketRequired: 'Select a market.', directionRequired: 'Select a direction.',
    entryRequired: 'Enter a valid entry date and time.', positiveNumber: 'Enter a number greater than zero.', nonnegativeNumber: 'Enter zero or a positive number.',
    closedExitRequired: 'A closed trade requires a valid exit date and time.', closedExitPriceRequired: 'A closed trade requires an exit price greater than zero.',
    exitBeforeEntry: 'Exit cannot be before entry.', screenshotLimit: 'Add no more than 10 screenshot links.', screenshotUrl: 'Use a valid HTTP or HTTPS URL on each line.',
  },
});

Object.assign(en.navigation, { strategies: 'Strategies & Setups' });
Object.assign(en.routes, { strategies: { title: 'Strategies & Setups', description: 'Manage reusable trade classifications and review their real performance.' } });
Object.assign(en.strategies = {}, {
  summary: 'Strategies and Setups summary', activeStrategies: 'Active Strategies', activeSetups: 'Active Setups', managedClosedTrades: 'Managed closed Trades', unlinkedClosedTrades: 'Unlinked closed Trades',
  strategyList: 'Managed Strategies', setups: 'Managed Setups', managedStrategy: 'Managed Strategy', managedSetup: 'Managed Setup', classification: 'Strategy classification',
  createStrategy: 'Create Strategy', editStrategy: 'Edit Strategy', saveStrategy: 'Save Strategy', createSetup: 'Create Setup', editSetup: 'Edit Setup', saveSetup: 'Save Setup',
  strategyName: 'Strategy name', setupName: 'Setup name', selectStrategy: 'Select a Strategy', parentRequired: 'Select a parent Strategy.', parentImmutable: 'A Setup cannot be moved to another Strategy after creation.',
  nameRequired: 'Enter a name.', archive: 'Archive', restore: 'Restore', strategySaved: 'Strategy saved.', setupSaved: 'Setup saved.', saveFailed: 'The managed classification could not be saved.',
  duplicateStrategy: 'A Strategy with this name already exists.', duplicateSetup: 'A Setup with this name already exists in this Strategy.',
  noStrategies: 'No managed Strategies yet', noStrategiesDetail: 'Create a Strategy to begin managing reusable trade classifications.', noSetups: 'No managed Setups yet', noSetupsDetail: 'Create a Setup within this Strategy when its execution pattern is reusable.',
  closedTrades: 'Closed Trades', openTrades: 'Open Trades', outcomes: 'Outcomes', outcomeRecord: '{{winners}} W / {{losers}} L / {{breakeven}} BE', setupCount: '{{count}} Setup', setupCount_other: '{{count}} Setups', closedCount: '{{count}} closed', tradeCount: '{{count}} Trade', tradeCount_other: '{{count}} Trades',
  legacyValues: 'Historical unlinked values', legacyDetail: 'These are preserved Trade text snapshots without managed IDs. They are read-only and are never matched automatically.', legacyStrategies: 'Legacy Strategy values', legacySetups: 'Legacy Setup values', noLegacyValues: 'No historical unlinked values.', unclassified: 'Unclassified',
  customLegacyValue: 'Custom or legacy text', hybridHelp: 'Managed selections keep a text snapshot; custom text remains supported.', quickAddBoundary: 'Quick Add keeps Setup selection in the full editor.',
  loading: 'Loading Strategies and Setups', loadFailed: 'Strategies and Setups could not be loaded', loadFailedDetail: 'Managed classifications and their performance are unavailable right now.', refreshFailed: 'Strategies could not be refreshed', staleVisible: 'The last available managed classifications remain visible.', setupsLoadFailed: 'Setups could not be loaded', legacyLoadFailed: 'Historical unlinked values could not be loaded', selectorLoadFailed: 'Managed classifications could not be loaded', customStillAvailable: 'Custom Strategy and Setup text remains available.',
});
Object.assign(en.trades.validation, { setupRequiresStrategy: 'A managed Setup requires a managed Strategy.' });
Object.assign(en.errors, { STRATEGY_NOT_FOUND: 'The Strategy was not found.', SETUP_NOT_FOUND: 'The Setup was not found.', STRATEGY_NAME_EXISTS: 'A Strategy with this name already exists.', SETUP_NAME_EXISTS: 'A Setup with this name already exists in this Strategy.', STRATEGY_ARCHIVED: 'Choose an active Strategy.', SETUP_ARCHIVED: 'Choose an active Setup.', SETUP_REQUIRES_STRATEGY: 'A managed Setup requires a managed Strategy.', SETUP_STRATEGY_MISMATCH: 'The Setup does not belong to the selected Strategy.' });

Object.assign(en.routes, {
  accountDetail: { title: 'Account details', description: 'Review account identity, tracked balance context, performance, and recent trades.' },
});
Object.assign(en.accounts, {
  accountName: 'Account name', companyBroker: 'Company / broker', baseCurrency: 'Base currency', openingBalance: 'Opening balance',
  defaultAccount: 'Default account', noDefault: 'No default account', setDefault: 'Set as default', archive: 'Archive account', restore: 'Restore account',
  activeAccounts: 'Active accounts', archivedAccounts: 'Inactive or archived accounts', inactiveArchivedAccounts: 'Inactive and archived accounts', closedOpen: 'Closed / open trades', trackedBalance: 'Tracked balance',
  trackedBalanceExplanation: 'Opening balance plus realized net PnL recorded in TradingLog. This is not a live broker balance.',
  mixedCurrencyDetail: 'These accounts use multiple currencies. Monetary totals are unavailable because no FX conversion is performed.',
  newAccountDialog: 'New Account', editAccount: 'Edit account', createAccount: 'Create account', accountSaved: 'Account saved.',
  confirmLifecycle: 'Confirm account change', archiveConfirm: 'Archive {{name}}? Historical trades and performance remain available.',
  restoreConfirm: 'Restore {{name}}? It will become selectable for new trades but will not become the default automatically.',
  activeAccount: 'Active account', archivedAccount: 'Archived account', lastTrade: 'Last trade', balanceContext: 'Balance context', performance: 'Performance',
  closedTrades: 'Closed trades', openTrades: 'Open trades', winners: 'Winners', losers: 'Losers', recentTrades: 'Recent trades',
  viewAllTrades: 'View all account trades', recentTradesFailed: 'Recent trades could not be loaded', noTrades: 'No trades for this account',
  noTradesDetail: 'Record a trade for this account to begin its performance history.', createTrade: 'Create trade for this account',
  loadingDetail: 'Loading account details', notFound: 'Account not found', notFoundDetail: 'This account is unavailable or belongs to another user.',
  backToAccounts: 'Back to accounts', accountUpdated: 'Account updated.', saveFailed: 'Account could not be saved.', loadFailed: 'Accounts could not be loaded',
  loadFailedDetail: 'Owned account metadata and performance are unavailable right now.',
  validation: { companyRequired: 'Enter a company or broker.', numberRequired: 'Enter an account number.', currency: 'Enter a three-letter currency code.', balance: 'Enter a valid opening balance.' },
});
Object.assign(en.analytics, {
  mixedCurrencies: 'Mixed currencies', mixedCurrenciesDetail: 'Monetary totals are unavailable because this scope contains multiple base currencies and TradingLog does not perform FX conversion.'
});
Object.assign(en.errors, { ACCOUNT_NOT_ACTIVE: 'Choose an active account.', ACCOUNT_STATE_INVALID: 'The account lifecycle or currency is invalid.', ACCOUNT_EXISTS: 'An account with this company and number already exists.' });

Object.assign(en.routes, { importRunDetail: { title: 'Import Run', description: 'Review durable results for a confirmed Trade import.' } });
en.importHistory = {
  title: 'Import history', privacy: 'Confirmed imports retain bounded results only. The original file and complete raw rows are not stored.',
  hashing: 'Hashing and parsing…',
  loading: 'Loading Import History', loadFailed: 'Import History could not be loaded.', empty: 'No import history yet.',
  viewDetails: 'View details', viewPrevious: 'View previous import', duplicateTitle: 'Exact file duplicate',
  duplicateDetail: 'This exact file was imported previously. Trade insertion has been blocked.',
  imported: 'Imported', skipped: 'Skipped', failed: 'Failed', importedRows: 'Imported rows', skippedRows: 'Skipped rows', failedRows: 'Failed rows',
  loadingDetail: 'Loading Import Run', notFound: 'Import Run not found', notFoundDetail: 'This Import Run is unavailable or belongs to another user.', back: 'Back to Import',
  noRawFile: 'The original file is not stored in TradingLog.', sourceType: 'Source type', fileSize: 'File size', started: 'Started', completedAt: 'Completed', totalRows: 'Total rows',
  mapping: 'Safe mapping metadata', rowResults: 'Row results', rowFilters: 'Filter row results', linkedTrade: 'View linked Trade', tradeUnavailable: 'The linked Trade is no longer available.', unknownFailure: 'The import could not be completed.',
  rowPagination: 'Import row pagination', previousRows: 'Previous rows', nextRows: 'Next rows',
  noMatchingRows: 'No row results match this filter.',
  status: { processing: 'Processing', completed: 'Completed', completed_with_errors: 'Completed with errors', failed: 'Failed' },
  rowStatus: { imported: 'Imported', skipped_duplicate: 'Skipped duplicate', failed_validation: 'Validation failed', failed_insert: 'Insert failed' },
  filters: { all: 'All', imported: 'Imported', skipped: 'Skipped', failed: 'Failed' },
  errors: { IMPORT_INVALID_FILE: 'The source file is invalid.', IMPORT_INVALID_MAPPING: 'The import mapping is invalid.', IMPORT_FATAL_ERROR: 'The import failed and Trade changes were rolled back.', IMPORT_NO_ROWS_IMPORTED: 'No source row produced a new Trade.', IMPORT_ROW_DUPLICATE: 'This row matched another row or an existing Trade.', IMPORT_ROW_VALIDATION_FAILED: 'This row did not pass Trade validation.', IMPORT_ROW_INSERT_FAILED: 'This row was not inserted because the transaction was rolled back.' },
};
Object.assign(en.errors, { IMPORT_DUPLICATE_FILE: 'This exact file has already been imported.', IMPORT_INVALID_FILE: 'The selected file is invalid.', IMPORT_INVALID_MAPPING: 'The import mapping is invalid.', IMPORT_FATAL_ERROR: 'The import failed and no Trade changes were committed.', IMPORT_ACCOUNT_NOT_FOUND: 'The selected Account was not found.', IMPORT_ACCOUNT_ARCHIVED: 'Choose an active Account for this import.' });

Object.assign(en.navigation, { system: 'System', settings: 'Settings' });
Object.assign(en.routes, {
  settings: { title: 'Settings', description: 'Manage language, appearance, timezone, and trading defaults.' },
});
en.settings = {
  language: 'Language', languageDirection: 'Language and direction', languageHelp: 'Changes apply immediately without reloading this page.',
  appearance: 'Appearance', appearanceHelp: 'Use the device setting or choose a fixed light or dark appearance.', theme: 'Theme',
  themeOptions: { system: 'Follow system', light: 'Light', dark: 'Dark' },
  timezone: 'Timezone', timezoneHelp: 'Calendar attribution for trades, Journal entries, Rule checks, Goals, and Daily Reviews uses this IANA timezone.',
  saveTimezone: 'Save timezone', timezoneUpdated: 'Timezone updated.', invalidTimezone: 'Enter a valid IANA timezone.', timezoneSaveFailed: 'The timezone could not be saved.',
  tradingDefaults: 'Trading defaults', tradingDefaultsHelp: 'These choices affect future Trade Editor visits and new Trade account selection.',
  defaultAccount: 'Default Account', applyDefaultAccount: 'Apply default Account', defaultAccountUpdated: 'Default Account updated.', defaultAccountSaveFailed: 'The default Account could not be updated.',
  accountsLoadFailed: 'Accounts could not be loaded.', noActiveAccounts: 'No active Accounts', noActiveAccountsDetail: 'Create or restore an Account before selecting a default.', manageAccounts: 'Manage Accounts',
  defaultTradeMode: 'Default Trade Editor mode', tradeModeHelp: 'This changes visual disclosure only; Trade data and validation are unchanged.',
  syncStatus: 'Preference synchronization', syncFailedDeviceOnly: 'Preference sync failed. Your choice is saved on this device only.',
  syncStates: { local: 'Using preferences saved on this device.', saving: 'Saving preference to your account…', synced: 'Saved across devices.', 'local-only': 'Saved on this device only.' },
  loadFailed: 'Settings could not be loaded.', loadFailedDetail: 'Your account preferences are unavailable right now. Local appearance and language remain available.',
};

export default en;
