import en from './en.js';

const he = {
  ...en,
  common: {
    ...en.common,
    save: 'שמירה', saveChanges: 'שמירת שינויים', saving: 'שומר…', cancel: 'ביטול', delete: 'מחיקה', deleting: 'מוחק…', edit: 'עריכה', close: 'סגירה', back: 'חזרה', retry: 'ניסיון נוסף', clearFilters: 'ניקוי מסננים', clearAll: 'ניקוי הכול', search: 'חיפוש', actions: 'פעולות', status: 'סטטוס', type: 'סוג', date: 'תאריך', from: 'מתאריך', to: 'עד תאריך', account: 'חשבון', allAccounts: 'כל החשבונות', symbol: 'סימול', market: 'שוק', direction: 'כיוון', outcome: 'תוצאה', strategy: 'אסטרטגיה', setup: 'סטאפ', timeframe: 'טווח זמן', notes: 'הערות', description: 'תיאור', name: 'שם', title: 'כותרת', content: 'תוכן', optional: 'אופציונלי', required: 'חובה', yes: 'כן', no: 'לא', active: 'פעיל', inactive: 'לא פעיל', archived: 'בארכיון', paused: 'מושהה', open: 'פתוחה', closed: 'סגורה', complete: 'הושלם', incomplete: 'לא הושלם', unavailable: 'לא זמין', noData: 'אין נתונים', loading: 'טוען…', today: 'היום', yesterday: 'אתמול', previous: 'הקודם', next: 'הבא', more: 'עוד', all: 'הכול', none: 'ללא', count: 'כמות', details: 'פרטים', filters: 'מסננים', refresh: 'רענון', export: 'ייצוא', import: 'ייבוא', create: 'יצירה', update: 'עדכון', view: 'צפייה', result: 'תוצאה', email: 'דוא״ל', password: 'סיסמה', displayName: 'שם תצוגה', company: 'חברה', accountNumber: 'מספר חשבון', accountName: 'שם החשבון', accountType: 'סוג חשבון', trades: 'עסקאות', entry: 'כניסה', exit: 'יציאה', entryPrice: 'מחיר כניסה', exitPrice: 'מחיר יציאה', quantity: 'כמות', fees: 'עמלות', netPnl: 'רווח והפסד נטו', grossPnl: 'רווח והפסד ברוטו', winRate: 'אחוז הצלחה', profitFactor: 'פקטור רווח', expectancy: 'תוחלת', averageR: 'ממוצע R', risk: 'סיכון', riskAmount: 'סכום בסיכון', stopLoss: 'סטופ לוס', takeProfit: 'יעד רווח', duration: 'משך', rMultiple: 'מכפיל R', long: 'לונג', short: 'שורט', breakeven: 'איזון', win: 'רווח', loss: 'הפסד', followed: 'בוצע לפי הכלל', broken: 'הכלל הופר', notApplicable: 'לא רלוונטי', achieved: 'הושג', missed: 'לא הושג', upcoming: 'עתידי', inProgress: 'בתהליך', atLeast: 'לפחות', atMost: 'לכל היותר', timezone: 'אזור זמן קלנדרי: {{timezone}}', pageControls: 'בקרי העמוד', unknown: 'לא ידוע', selected: 'נבחר', language: 'שפה', english: 'English', hebrew: 'עברית', new: 'חדש', record: 'תיעוד', calendar: 'לוח שנה', timeline: 'ציר זמן', summary: 'סיכום', total: 'סה״כ', value: 'ערך', target: 'יעד', current: 'נוכחי', progress: 'התקדמות', linkedTrades: 'עסקאות מקושרות', tags: 'תגיות', scope: 'היקף', rule: 'כלל', goal: 'יעד', journal: 'יומן', review: 'סיכום', period: 'תקופה', created: 'נוצר', updated: 'עודכן', pageOf: 'עמוד {{page}} מתוך {{pages}}', records: '{{count}} רשומות', activeCount: '{{count}} פעילים', allTime: 'כל התקופה', thisWeek: 'השבוע', lastWeek: 'השבוע שעבר', thisMonth: 'החודש', moreFilters: 'מסננים נוספים', fewerFilters: 'פחות מסננים', noChange: 'ללא שינוי', gain: 'רווח', lossValue: 'הפסד'
  },
  navigation: { trading: 'מסחר', manage: 'ניהול', insights: 'תובנות', dashboard: 'לוח בקרה', trades: 'עסקאות', dailyReview: 'סיכום יומי', accounts: 'חשבונות', import: 'ייבוא', analytics: 'ניתוחים', journal: 'יומן וסקירות', rules: 'כללי מסחר ועמידה', goals: 'יעדים', main: 'ניווט ראשי', primary: 'ניווט ראשי', moreNavigation: 'ניווט נוסף', moreDestinations: 'יעדים נוספים', sidebar: 'סרגל היישום', collapse: 'כיווץ הניווט', expand: 'הרחבת הניווט' },
  routes: {
    dashboard: { title: 'לוח בקרה', description: 'סקירת ביצועי המסחר בטווח הנוכחי.' }, trades: { title: 'עסקאות', description: 'איתור, סינון, ייצוא וניהול עסקאות מתועדות.' }, dailyReview: { title: 'סיכום יומי', description: 'סקירת יום המסחר הנבחר, תיעוד האירועים והכנה לסשן הבא.' }, tradeDetail: { title: 'פרטי עסקה', description: 'סקירת ההקשר והתוצאה של העסקה המתועדת.' }, accounts: { title: 'חשבונות', description: 'ניהול החשבונות המשמשים לארגון פעילות המסחר.' }, import: { title: 'ייבוא', description: 'ייבוא קובצי עסקאות מהברוקר לחשבון קיים.' }, analytics: { title: 'ניתוחים', description: 'ניתוח ביצועי מסחר לפי שוק, כיוון, אסטרטגיה, תזמון וחשבון.' }, journal: { title: 'יומן וסקירות', description: 'תיעוד הערות וסקירות מובנות וקישורן לעסקאות הרלוונטיות.' }, rules: { title: 'כללי מסחר ועמידה', description: 'הגדרת כללי מסחר, תיעוד התוצאות ומדידת עקביות התהליך לאורך זמן.' }, goals: { title: 'יעדים', description: 'הגדרת יעדי מסחר ותהליך מדידים ומעקב אחר התקדמות המבוססת על הפעילות האמיתית.' }
  },
  auth: { signInJournal: 'כניסה ליומן המסחר', createJournal: 'יצירת יומן המסחר שלך', signIn: 'כניסה', signingIn: 'מתחבר…', createAccount: 'יצירת חשבון', creatingAccount: 'יוצר חשבון…', noAccount: 'אין לך חשבון?', createOne: 'יצירת חשבון', alreadyAccount: 'כבר יש לך חשבון?', passwordMin: 'הסיסמה חייבת להכיל לפחות 8 תווים.', passwordLabel: 'סיסמה * (לפחות 8 תווים)', emailLabel: 'דוא״ל *', loginFailed: 'הכניסה נכשלה.', signupFailed: 'יצירת החשבון נכשלה.', loggedOut: 'התנתקת מהמערכת.' },
  shell: { breadcrumb: 'פירורי לחם', searchCommand: 'חיפוש או הפעלת פקודה', searchCommands: 'חיפוש פקודות', commandPlaceholder: 'ניווט או הפעלת פעולה זמינה', availableCommands: 'פקודות זמינות', noCommands: 'לא נמצאו פקודות תואמות', commandHelp: 'השתמשו בחצים למעלה ולמטה כדי לנוע, Enter לפתיחה ו־Escape לסגירה.', goTo: 'מעבר אל {{label}}', newJournal: 'רשומת יומן חדשה', newJournalDescription: 'פתיחת טופס רשומה ביומן וסקירות', newRule: 'כלל חדש', newRuleDescription: 'יצירת כלל מסחר', recordCheck: 'תיעוד בדיקת כלל', recordCheckDescription: 'תיעוד האם כלל המסחר קוים', newGoal: 'יעד חדש', newGoalDescription: 'יצירת יעד מדיד', lightTheme: 'מעבר לערכת נושא בהירה', darkTheme: 'מעבר לערכת נושא כהה', logout: 'התנתקות', notifications: 'התראות', dismissNotification: 'סגירת ההתראה', closeDialog: 'סגירת החלון', languageLabel: 'בחירת שפת היישום' },
  status: { active: 'פעיל', inactive: 'לא פעיל', archived: 'בארכיון', paused: 'מושהה', open: 'פתוחה', closed: 'סגורה', complete: 'הושלם', incomplete: 'לא הושלם', upcoming: 'עתידי', in_progress: 'בתהליך', achieved: 'הושג', missed: 'לא הושג', followed: 'בוצע לפי הכלל', broken: 'הכלל הופר', not_applicable: 'לא רלוונטי', long: 'לונג', short: 'שורט', win: 'רווח', loss: 'הפסד', breakeven: 'איזון', funded: 'ממומן', evaluation: 'הערכה', demo: 'דמו', live: 'חי', trade: 'עסקה', daily: 'יומי', general: 'כללי', note: 'הערה', trade_review: 'סקירת עסקה', daily_review: 'סיכום יומי', weekly_review: 'סיכום שבועי' },
  states: { noMatching: 'לא נמצאו תוצאות תואמות', nothingYet: 'עדיין אין כאן תוכן', somethingWrong: 'אירעה שגיאה', stillAvailable: 'עדיין זמין: {{available}}' },
  validation: { required: 'השדה {{field}} הוא חובה.', invalidDate: 'יש להזין תאריך תקין.', invalidNumber: 'יש להזין מספר תקין.', dateRange: 'תאריך הסיום לא יכול להיות לפני תאריך ההתחלה.', maxLength: '{{field}} מוגבל ל־{{max}} תווים.', passwordMin: 'הסיסמה חייבת להכיל לפחות 8 תווים.' },
  errors: { unknown: 'אירעה שגיאה. אפשר לנסות שוב.', network: 'לא ניתן להגיע לשרת. אפשר לנסות שוב.', unauthorized: 'פג תוקף החיבור. יש להתחבר מחדש.', DAILY_REVIEW_DUPLICATE_ENTRIES: 'קיים יותר מסיכום יומי אחד לתאריך הזה. יש לפתור את הכפילויות ביומן לפני שממשיכים.', saveFailed: 'לא ניתן לשמור את השינויים.', deleteFailed: 'לא ניתן למחוק את הפריט.', loadFailed: 'לא ניתן לטעון את הנתונים.' },
  dashboard: { performance: 'ביצועים', recentTrades: 'עסקאות אחרונות', noTrades: 'אין עסקאות בתקופה הזו', noTradesDetail: 'תעדו עסקה או שנו את התקופה כדי לראות ביצועים.', dailyPnl: 'רווח והפסד יומי', periodPnl: 'רווח והפסד לתקופה', closedTrades: 'עסקאות סגורות', openTrades: 'עסקאות פתוחות', winners: 'עסקאות מרוויחות', losers: 'עסקאות מפסידות', bestTrade: 'העסקה הטובה ביותר', worstTrade: 'העסקה הגרועה ביותר', equityCurve: 'רווח והפסד נטו מצטבר', calendar: 'לוח מסחר', addTrade: 'הוספת עסקה', today: 'היום', wtd: 'מתחילת השבוע', mtd: 'מתחילת החודש', custom: 'מותאם אישית' },
  trades: { addTrade: 'הוספת עסקה', editTrade: 'עריכת עסקה', cancelEdit: 'ביטול עריכה', deleteTrade: 'מחיקת עסקה', tradeDeleted: 'העסקה נמחקה.', tradeUpdated: 'העסקה עודכנה.', createFailed: 'יצירת העסקה נכשלה.', updateFailed: 'עדכון העסקה נכשל.', deleteFailed: 'מחיקת העסקה נכשלה.', deleteConfirm: 'למחוק את העסקה לצמיתות?', deleteConfirmShort: 'למחוק את העסקה?', exportCsv: 'ייצוא CSV', exportFailed: 'הייצוא נכשל.', recordedCaption: 'עסקאות מתועדות עם חשבון, כניסה, תוצאה, סטטוס ופעולות', noTrades: 'לא נמצאו עסקאות', noTradesDetail: 'אין עסקאות התואמות למסננים שנבחרו.', loading: 'טוען עסקאות', details: 'פרטי עסקה', financialResult: 'תוצאה כספית', entryExit: 'כניסה ויציאה', planOutcome: 'תכנון מול תוצאה', context: 'הקשר המסחר', emotions: 'רגשות', attachments: 'קישורים לצילומי מסך', attachment: 'קובץ {{number}} · {{host}}', openAttachment: 'פתיחת קובץ {{number}} מאת {{host}} בכרטיסייה חדשה', back: 'חזרה לעסקאות', loadError: 'לא ניתן לטעון את פרטי העסקה', unavailableRecord: 'רשומת העסקה אינה זמינה כרגע.', notFound: 'העסקה לא נמצאה', notFoundDetail: 'רשומת העסקה אינה זמינה או שנמחקה.', openDetails: 'פתיחת פרטי העסקה {{symbol}}', sortBy: 'מיון לפי {{label}}{{status}}', currently: ', כרגע {{order}}', ascending: 'עולה', descending: 'יורד', marketHelp: 'סוג השוק של העסקה.', exitHelp: 'יש להשאיר את שני שדות היציאה ריקים לעסקה פתוחה.', screenshotHelp: 'כתובת אחת בכל שורה.', screenshots: 'קישורים לצילומי מסך (אופציונלי)' },
  accounts: { newAccount: 'חשבון חדש', editAccount: 'עריכת חשבון', deleteAccount: 'מחיקת חשבון', accountCreated: 'החשבון נוצר.', accountUpdated: 'החשבון עודכן.', accountDeleted: 'החשבון נמחק.', loadFailed: 'טעינת החשבונות נכשלה.', saveFailed: 'שמירת החשבון נכשלה.', deleteFailed: 'מחיקת החשבון נכשלה.', noAccounts: 'עדיין אין חשבונות', noAccountsDetail: 'יש ליצור חשבון לפני תיעוד או ייבוא עסקאות.', hasTrades: 'בחשבון הזה יש {{count}} עסקאות. יש לשייך אותן מחדש או למחוק אותן לפני מחיקת החשבון.', permanentDelete: 'למחוק לצמיתות את {{account}}? לא ניתן לבטל פעולה זו.', tradingAccounts: 'חשבונות מסחר', tradesCount: 'מספר עסקאות' },
  analytics: { summary: 'סיכום ביצועים', netPnl: 'רווח והפסד נטו', winRate: 'אחוז הצלחה', profitFactor: 'פקטור רווח', expectancy: 'תוחלת', averageWin: 'רווח ממוצע', averageLoss: 'הפסד ממוצע', closedTrades: 'עסקאות סגורות', cumulative: 'רווח והפסד נטו מצטבר', dollarDistribution: 'התפלגות רווח והפסד בדולר', rDistribution: 'התפלגות R', breakdown: 'פילוח ביצועים', calendar: 'לוח מסחר', noData: 'אין נתוני ניתוח לטווח הזה', noDataDetail: 'תעדו עסקאות סגורות או שנו את הטווח שנבחר.', timezoneHelp: 'תאריכים קלנדריים משתמשים ב־{{timezone}}.', bySymbol: 'לפי סימול', byMarket: 'לפי שוק', byDirection: 'לפי כיוון', byStrategy: 'לפי אסטרטגיה', bySetup: 'לפי סטאפ', byTimeframe: 'לפי טווח זמן', byAccount: 'לפי חשבון', byCompany: 'לפי חברה', byWeekday: 'לפי יום בשבוע' },
  journal: { newEntry: 'רשומת יומן חדשה', editEntry: 'עריכת רשומת יומן', deleteEntry: 'מחיקת רשומה', entrySaved: 'רשומת היומן נשמרה.', entryDeleted: 'רשומת היומן נמחקה.', saveFailed: 'לא ניתן לשמור את רשומת היומן.', deleteFailed: 'לא ניתן למחוק את רשומת היומן.', deleteConfirm: 'למחוק את רשומת היומן?', noEntries: 'עדיין אין רשומות ביומן', noEntriesDetail: 'צרו הערה או סקירה כדי להתחיל את ציר הזמן ביומן.', filteredEmpty: 'אין רשומות יומן התואמות למסננים הנוכחיים', entryType: 'סוג רשומה', entryDate: 'תאריך הרשומה', completeOnly: 'הושלמו בלבד', incompleteOnly: 'לא הושלמו בלבד', allCompletion: 'כל מצבי ההשלמה', searchPlaceholder: 'חיפוש בכותרת, בתוכן או בתגיות', tagsHelp: 'יש להפריד תגיות בפסיקים.', linkedTradesHelp: 'בחרו את העסקאות המתוארות ברשומה.', journalEntry: 'רשומת יומן' },
  rules: { newRule: 'כלל חדש', editRule: 'עריכת כלל', recordCheck: 'תיעוד בדיקת כלל', editCheck: 'עריכת בדיקת כלל', adherence: 'עמידה בכללים', activeRules: 'כללים פעילים', inactiveRules: 'כללים לא פעילים', history: 'היסטוריית בדיקות', noRules: 'עדיין אין כללי מסחר', noRulesDetail: 'צרו כלל כדי להתחיל למדוד עמידה בכללים.', noChecks: 'אין בדיקות כללים בתקופה הזו', followed: 'בוצע לפי הכלל', broken: 'הכלל הופר', notApplicable: 'לא רלוונטי', eligibleChecks: 'בדיקות רלוונטיות', ruleCreated: 'הכלל נוצר.', ruleUpdated: 'הכלל עודכן.', ruleDeleted: 'הכלל נמחק.', checkSaved: 'בדיקת הכלל נשמרה.', deleteConfirm: 'למחוק את הכלל?', hasChecks: 'לא ניתן למחוק כלל שיש לו בדיקות.', ruleName: 'שם הכלל', checkDate: 'תאריך הבדיקה', linkedTrade: 'עסקה מקושרת', linkedJournal: 'רשומת יומן מקושרת', noEligible: 'אין בדיקות רלוונטיות' },
  goals: { newGoal: 'יעד חדש', editGoal: 'עריכת יעד', deleteGoal: 'מחיקת יעד', goalCreated: 'היעד נוצר.', goalUpdated: 'היעד עודכן.', goalDeleted: 'היעד נמחק.', saveFailed: 'לא ניתן לשמור את היעד.', deleteFailed: 'לא ניתן למחוק את היעד.', deleteConfirm: 'למחוק את היעד? רשומות המקור יישארו ללא שינוי.', noGoals: 'עדיין אין יעדים', noGoalsDetail: 'צרו יעד מדיד כדי להתחיל לעקוב אחר התקדמות מהפעילות שלכם.', filteredEmpty: 'אין יעדים התואמים למסננים הנוכחיים', metric: 'מדד', targetValue: 'ערך יעד', startDate: 'תאריך התחלה', endDate: 'תאריך סיום', comparison: 'השוואה', storedStatus: 'סטטוס שמור', derivedState: 'מצב נוכחי', currentValue: 'ערך נוכחי', difference: 'פער מהיעד', pause: 'השהיה', resume: 'המשך', archive: 'העברה לארכיון', restore: 'שחזור', withinLimit: 'בתוך הגבול', overLimit: 'מעל הגבול', maxAllowed: 'מקסימום מותר', unavailable: 'הערך הנוכחי אינו זמין.', progressLabel: '{{name}}: נוכחי {{current}}, יעד {{target}}, {{percent}}%, {{state}}', no_closed_trades: 'אין עסקאות סגורות בתקופת היעד.', no_r_data: 'אין עסקאות עם נתוני R בתקופת היעד.', no_eligible_rule_checks: 'אין בדיקות כללים רלוונטיות בתקופת היעד.', source_unavailable: 'לא ניתן לחשב את מקור הנתונים כרגע.' },
  importPage: { title: 'ייבוא עסקאות', selectFile: 'בחירת קובץ', mapping: 'מיפוי עמודות', preview: 'תצוגה מקדימה', results: 'תוצאות הייבוא', chooseAccount: 'בחירת חשבון', chooseFile: 'בחירת קובץ CSV', upload: 'העלאה ותצוגה מקדימה', importing: 'מייבא…', importTrades: 'ייבוא עסקאות', cancelImport: 'ביטול הייבוא', file: 'קובץ', rows: 'שורות', validRows: 'שורות תקינות', invalidRows: 'שורות שגויות', duplicates: 'כפילויות', errors: 'שגיאות', complete: 'הייבוא הושלם', failed: 'הייבוא נכשל', requiredColumns: 'עמודות חובה', optionalColumns: 'עמודות אופציונליות' },
  dailyReview: { sessionNotes: 'הערות הסשן', wentWell: 'מה עבד טוב', improve: 'מה כדאי לשפר', nextPlan: 'תוכנית לסשן הבא', emotions: 'רגשות', mistakes: 'טעויות', saveReview: 'שמירת הסיכום היומי', saved: 'הסיכום היומי נשמר.', saveFailed: 'לא ניתן לשמור את הסיכום היומי.', noReview: 'עדיין לא נשמר סיכום יומי', noReviewDetail: 'תעדו מה קרה והתכוננו לסשן הבא.', daySummary: 'סיכום היום', tradesTaken: 'עסקאות שבוצעו', rulesChecks: 'כללים ובדיקות', reviewSection: 'הערות הסיכום', recordCheck: 'תיעוד בדיקה', noRules: 'אין כללים פעילים', noChecks: 'אין בדיקות מתועדות לתאריך הזה', noTrades: 'אין עסקאות בתאריך הזה', completion: 'סימון הסיכום כהושלם', previousDay: 'היום הקודם', nextDay: 'היום הבא', openToday: 'פתיחת היום', invalidDate: 'תאריך הסיכום היומי אינו תקין.', invalidDateDetail: 'יש להשתמש בתאריך קלנדרי תקין בפורמט YYYY-MM-DD.', calendarTimezone: 'אזור זמן קלנדרי: {{timezone}}', closedTrades: 'עסקאות סגורות', openTrades: 'עסקאות פתוחות', winners: 'עסקאות מרוויחות', losers: 'עסקאות מפסידות', bestTrade: 'העסקה הטובה ביותר', worstTrade: 'העסקה הגרועה ביותר', feeTotal: 'עמלות', adherence: 'עמידה בכללים', checkCount: '{{count}} בדיקות', latest: 'אחרון: {{outcome}}', customEmotion: 'הוספת רגש מותאם', customMistake: 'הוספת טעות מותאמת', add: 'הוספה', maxItems: 'אפשר לבחור עד {{max}} פריטים.', contentRequired: 'הערות הסשן הן שדה חובה.' }
};

Object.assign(he.common, {
  maximum: 'מקסימום',
  allStatuses: 'כל הסטטוסים',
  restOfApp: 'שאר חלקי TradingLog',
});

Object.assign(he.goals, {
  deleteNamedConfirm: 'למחוק את „{{name}}”? המחיקה מסירה רק את הגדרת היעד.',
  clearFilterDetail: 'נקו את המסננים הנוכחיים כדי לחזור לכל היעדים.',
  overLimitBy: 'חריגה של',
  remainingAllowance: 'יתרה מותרת',
  targetAchieved: 'היעד הושג',
  progressUnavailable: 'אחוז התקדמות אינו משמעותי לערך היעד הזה.',
  summary: 'סיכום יעדים',
  loadingSummary: 'טוען סיכום יעדים',
  loadingMetric: 'טוען מדד יעד',
  filters: 'מסנני יעדים',
  search: 'חיפוש יעדים',
  statusFilter: 'סטטוס יעד',
  metricFilter: 'מדד יעד',
  allMetrics: 'כל המדדים',
  refreshing: 'מרענן יעדים…',
  refreshFailed: 'לא ניתן לרענן את היעדים',
  staleVisible: 'היעדים האחרונים הזמינים נשארים מוצגים.',
  availableActions: 'מסננים ופעולות היעדים הקיימים',
  loadFailed: 'לא ניתן לטעון את היעדים',
  loadFailedDetail: 'הגדרות היעדים וחישובי ההתקדמות אינם זמינים כרגע.',
  activeUpcoming: 'פעילים ועתידיים',
  outcomes: 'תוצאות',
  pausedArchived: 'מושהים ובארכיון',
});

Object.assign(he.common, { any: 'כל תאריך' });
Object.assign(he.analytics, {
  loadingScope: 'טוען את סיכום טווח הניתוחים', scopeFailed: 'לא ניתן לטעון את סיכום הטווח', closedUnavailable: 'מספר העסקאות הסגורות אינו זמין.', scopeAvailable: 'בקרי הטווח ורכיבי ניתוח שנטענו בהצלחה', scopeSummary: 'סיכום טווח הניתוחים', dateRange: 'טווח תאריכים', accountScope: 'טווח חשבונות', calendarTimezone: 'אזור זמן קלנדרי', allCompanies: 'כל החברות', period: 'תקופת הניתוח', customDates: 'תאריכים מותאמים לניתוח', accountsLoadFailed: 'לא ניתן לטעון אפשרויות חשבון. ניתוח כלל החשבונות עדיין זמין.', retryAccounts: 'ניסיון נוסף לטעינת חשבונות', loadFailed: 'לא ניתן לטעון את הניתוחים', loadFailedDetail: 'סיכום הטווח, פילוח הביצועים והתפלגות R נכשלו.', controlsAvailable: 'בקרי חשבון ותקופה', noClosedScope: 'אין עסקאות סגורות בטווח הזה', noClosedScopeDetail: 'בחרו חשבון או טווח תאריכים אחר כדי לנתח תוצאות מתועדות.', weekday: 'יום בשבוע', breakdownDetails: 'פרטי הפילוח לפי הממד שנבחר', group: 'קבוצה', viewDetails: 'הצגת פרטי הפילוח', dimensionAnalysis: 'ניתוח לפי ממד', dimensionDescription: 'רווח והפסד נטו ותוצאות של עסקאות סגורות לפי {{dimension}}.', dimensionControl: 'ניתוח ביצועים לפי ממד', dimensionFailed: 'לא ניתן לטעון את ניתוח הממד', dimensionUnavailable: 'הפילוח לפי {{dimension}} אינו זמין.', dimensionAvailable: 'בקרי הטווח והתפלגות R', noDimension: 'אין פילוח לפי {{dimension}}', noDimensionDetail: 'אין בטווח הזה עסקאות סגורות שאפשר לקבץ לפי הממד.', closedTradeSummary: '{{count}} עסקה סגורה · {{rate}} הצלחה', closedTradeSummary_other: '{{count}} עסקאות סגורות · {{rate}} הצלחה', tradeCount: 'עסקה אחת', tradeCount_other: '{{count}} עסקאות', loadingR: 'טוען התפלגות R', rFailed: 'לא ניתן לטעון את התפלגות R', rFailedDetail: 'טווחי R השמורים אינם זמינים לטווח הזה.', rAvailable: 'בקרי הטווח וניתוח לפי ממד', rUnavailable: 'נתוני R אינם זמינים', rUnavailableDetail: 'קיימות עסקאות סגורות בטווח, אך לאף אחת אין מכפיל R שמור. נתון סיכון חסר אינו נחשב ל־0R.', rDescription: 'תוצאות שמורות עבור {{count}} עסקאות סגורות, ביחס לסיכון המתוכנן.'
});
Object.assign(he.importPage, {
  selectUpload: 'בחירה והעלאה', done: 'הושלם', progress: 'התקדמות הייבוא', noRows: 'אין שורות לתצוגה מקדימה.', previewTable: 'תצוגה מקדימה של עסקאות לייבוא', broker: 'ברוקר', csvFile: 'קובץ CSV', parsing: 'מנתח…', selectBrokerError: 'יש לבחור ברוקר.', selectFileError: 'יש לבחור קובץ CSV.', selectAccountError: 'יש לבחור חשבון לעסקאות האלה.', parseFailed: 'ניתוח קובץ ה־CSV נכשל.', totalRows: 'סך השורות בקובץ', uniqueRows: 'שורות ייחודיות בקובץ', inFileDuplicates: 'כפילויות בתוך הקובץ', previewCount: 'תצוגה מקדימה ({{shown}} מתוך {{total}} שורות ייחודיות)', assignAccount: 'שיוך לחשבון *', assignAccountHelp: 'כל העסקאות המיובאות ישויכו לחשבון הזה.', importCount: 'ייבוא עסקה אחת', importCount_other: 'ייבוא {{count}} עסקאות', startOver: 'התחלה מחדש', importedCount: 'עסקאות שיובאו', existingCount: 'כבר היו קיימות', viewTrades: 'הצגת עסקאות', importMore: 'ייבוא נוסף'
});
Object.assign(he.rules, {
  overallAdherence: 'עמידה כוללת', summary: 'סיכום עמידה בכללים', notApplicableDetail: 'כל הבדיקות בתקופה אינן רלוונטיות, ולכן הן אינן נכללות במכנה של חישוב העמידה.', recordToMeasure: 'תעדו מה קרה כדי להתחיל למדוד עמידה בכללים.', reactivateHelp: 'יש להפעיל מחדש את הכלל לפני תיעוד בדיקה חדשה.', noLinkedContext: 'אין הקשר מקושר', overview: 'סקירה', detailsUnavailable: 'פרטי הכלל אינם זמינים. נסו לטעון מחדש את רשימת הכללים לפני העריכה.', period: 'תקופת הכללים', customDates: 'תאריכים מותאמים לכללים', view: 'תצוגת כללים', invalidRange: 'טווח התאריכים אינו תקין', managementForms: 'ניהול כללים וטפסים', perRule: 'עמידה לפי כלל', recentChecks: 'בדיקות אחרונות', management: 'ניהול כללים', search: 'חיפוש כללים', statusFilter: 'סטטוס כלל', scopeFilter: 'היקף כלל', allScopes: 'כל ההיקפים'
});
Object.assign(he.goals, { goalName: 'שם היעד' });
Object.assign(he.accounts, { newAccountDialog: 'חשבון חדש' });
Object.assign(he.analytics, { expectancyDescription: 'ממוצע רווח והפסד נטו לעסקה סגורה' });
Object.assign(he.dashboard, { loadFailed: 'לא ניתן לטעון את נתוני לוח הבקרה', loadFailedDetail: 'בקשות הניתוח נכשלו. ייתכן שלוח השנה, שנטען בנפרד, עדיין זמין.' });
Object.assign(he.goals, { newGoalDialog: 'יעד חדש', editGoalDialog: 'עריכת יעד', createGoal: 'יצירת יעד', saveGoal: 'שמירת יעד', targetRequired: 'יש להזין ערך יעד.', wholeCount: 'יעד ספירה חייב להיות מספר שלם.' });
Object.assign(he.journal, { newEntryDialog: 'רשומה חדשה ביומן', editEntryDialog: 'עריכת רשומת יומן', createEntry: 'יצירת רשומה' });
Object.assign(he.trades, { loadFailed: 'לא ניתן לטעון את העסקאות', filteredEmpty: 'אין עסקאות התואמות למסננים הנוכחיים', filters: 'מסנני עסקאות', loadingDetails: 'טוען את פרטי העסקה' });
Object.assign(he.dashboard, { addTrade: 'הוספת עסקה' });
Object.assign(he.trades, { entryTime: 'שעת כניסה', exitTime: 'שעת יציאה', outcomeR: 'תוצאה ב־R' });
Object.assign(he.dashboard, { loadingMetrics: 'טוען מדדי לוח בקרה', period: 'תקופת לוח הבקרה', customDates: 'תאריכים מותאמים ללוח הבקרה' });
Object.assign(he.journal, { timeline: 'ציר הזמן של היומן', calendarHelp: 'השבועות מתחילים ביום ראשון. בחרו יום כדי לסקור את הרשומות שלו.', previousMonth: 'החודש הקודם', nextMonth: 'החודש הבא', noEntriesMonth: 'אין רשומות יומן בחודש הזה' });
Object.assign(he.analytics, {
  breakdownDescription: 'רווח והפסד נטו של עסקאות סגורות לפי ממד נתמך.', loadingEquity: 'טוען גרף רווח והפסד ממומש מצטבר', equityFailed: 'לא ניתן לטעון את הרווח וההפסד המצטבר', equityFailedDetail: 'הסכום המצטבר של העסקאות הסגורות אינו זמין.', dashboardAvailable: 'בקרי לוח הבקרה ורכיבים אחרים שנטענו בהצלחה', noEquity: 'אין רווח והפסד ממומש להצגה', noEquityDetail: 'אין בטווח שנבחר עסקאות סגורות עבור הגרף.', cumulativeDescription: 'סכום מצטבר של רווח והפסד נטו מעסקאות סגורות בטווח שנבחר.', loadingDistribution: 'טוען התפלגות רווח והפסד', distributionFailed: 'לא ניתן לטעון את התפלגות הרווח וההפסד', distributionFailedDetail: 'טווחי הרווח וההפסד בדולר אינם זמינים.', noDistribution: 'עדיין אין התפלגות רווח והפסד', noDistributionDetail: 'נדרשות עסקאות סגורות כדי למלא את טווחי הרווח וההפסד.', distributionDescription: 'עסקאות סגורות מקובצות לפי הרווח או ההפסד נטו בדולר.', loadingCalendar: 'טוען לוח מסחר', calendarFailed: 'לא ניתן לטעון את לוח המסחר', calendarFailedDetail: 'הרווח וההפסד היומי הממומש אינו זמין לחודש הזה.', dailyRealized: 'רווח והפסד יומי ממומש', calendarDescription: 'רווח והפסד נטו מעסקאות סגורות לפי תאריך כניסה; השבועות מתחילים ביום ראשון.', noCalendarTrades: 'לא תועדו עסקאות סגורות בחודש הקלנדרי הזה.', tradingDays: 'יום מסחר אחד בשנת {{year}}.', tradingDays_other: '{{count}} ימי מסחר בשנת {{year}}.', weekdays: { sun: 'א׳', mon: 'ב׳', tue: 'ג׳', wed: 'ד׳', thu: 'ה׳', fri: 'ו׳', sat: 'ש׳' }
});

Object.assign(he.rules, {
  tabRules: 'כללים',
  createRule: 'יצירת כלל',
  saveRule: 'שמירת כלל',
  recordCheckSubmit: 'תיעוד בדיקה',
  saveCheck: 'שמירת בדיקה',
  checkDeleted: 'בדיקת הכלל נמחקה.',
  recordCheckDialog: 'תיעוד בדיקת כלל',
});

Object.assign(he.journal, {
  loadingTimeline: 'טוען את ציר הזמן של היומן', loadingEntry: 'טוען רשומת יומן', loadingTitle: 'טוען כותרת', loadingContent: 'טוען תוכן',
  controls: 'בקרי היומן', view: 'תצוגת היומן', search: 'חיפוש ברשומות היומן', completionStatus: 'סטטוס השלמה', fromDate: 'מתאריך', toDate: 'עד תאריך',
  refreshFailed: 'לא ניתן לרענן את רשומות היומן', lastTimelineVisible: 'ציר הזמן האחרון שנטען נשאר מוצג.', filtersCalendarForm: 'מסננים, לוח שנה וטופס רשומה',
  entryCount: 'רשומה אחת', entryCount_other: '{{count}} רשומות', refreshingTimeline: 'מרענן את ציר הזמן…', invalidRange: 'טווח התאריכים אינו תקין', invalidRangeDetail: 'בחרו תאריך סיום זהה לתאריך ההתחלה או מאוחר ממנו.', entriesFiltersUnchanged: 'הרשומות והמסננים הקיימים נשארו ללא שינוי', loadFailed: 'לא ניתן לטעון את רשומות היומן', loadFailedDetail: 'הבקשה לציר הזמן נכשלה.', calendarAndForm: 'לוח שנה וטופס רשומה',
  deleteNamedConfirm: 'למחוק את „{{title}}”?', loadingCalendar: 'טוען את לוח השנה של היומן', calendarLoadFailed: 'לא ניתן לטעון את לוח השנה של היומן', monthCountsUnavailable: 'ספירת הרשומות החודשית אינה זמינה.', timelineAndForm: 'ציר הזמן וטופס הרשומה', calendarRefreshFailed: 'לא ניתן לרענן את לוח השנה של היומן', lastMonthVisible: 'החודש האחרון שנטען נשאר מוצג.', refreshingCalendar: 'מרענן את לוח השנה…', entriesForMonth: 'רשומות יומן עבור {{month}}', daySummaryLabel: '{{date}}, {{total}} רשומות, {{complete}} הושלמו, {{incomplete}} לא הושלמו', selectedDay: 'היום שנבחר', selectDay: 'בחרו יום בלוח השנה', selectDayDetail: 'בחרו יום כדי לראות את רשומות היומן שלו.', loadingSelectedDay: 'טוען רשומות ליום שנבחר', selectedDayLoadFailed: 'לא ניתן לטעון את היום שנבחר', selectedDayUnavailable: 'הרשומות ליום זה אינן זמינות.', monthNavigation: 'ספירות חודשיות וניווט', noEntriesDay: 'אין רשומות יומן ביום הזה', noEntriesDayDetail: 'לא נשמרו רשומות בתאריך שנבחר.', selectedDayRefreshFailed: 'לא ניתן לרענן את היום שנבחר', lastEntriesVisible: 'הרשומות האחרונות שנטענו נשארו מוצגות.',
  chooseEntryType: 'בחרו סוג רשומה.', chooseDate: 'בחרו תאריך ליומן.', enterTitle: 'הזינו כותרת.', enterContent: 'הזינו תוכן ליומן.', tagsPlaceholder: 'תהליך, סבלנות', searchTrades: 'חיפוש עסקאות לפי סימול', searchBySymbol: 'חיפוש לפי סימול', selectedTradesCount: '{{count}} מתוך {{max}} נבחרו', loadingRecentTrades: 'טוען עסקאות אחרונות…', tradesLoadFailed: 'לא ניתן לטעון עסקאות. הבחירות הקיימות נשמרו.', noTradeMatches: 'אין עסקאות בבעלותכם התואמות לחיפוש הסימול.', availableTrades: 'עסקאות זמינות'
});

Object.assign(he.rules, {
  loadingSummary: 'טוען סיכום עמידה בכללים', loadingMetric: 'טוען מדד עמידה', lastCheck: 'בדיקה אחרונה', ruleAdherenceLabel: 'עמידה בכלל {{name}}', historyPages: 'עמודי היסטוריית בדיקות', deleteNamedConfirm: 'למחוק את „{{name}}”? אי אפשר למחוק כללים שיש להם בדיקות היסטוריות.', deleteCheckConfirm: 'למחוק את בדיקת „{{outcome}}” עבור „{{name}}”?',
  fullLoadFailed: 'לא ניתן לטעון את כללי המסחר והעמידה בהם', fullLoadFailedDetail: 'הבקשות לכללים, לעמידה ולהיסטוריית הבדיקות נכשלו.', periodAndForms: 'בקרי תקופה וטפסים', summaryLoadFailed: 'לא ניתן לטעון את סיכום העמידה', rulesHistoryAvailable: 'הכללים והיסטוריית הבדיקות עדיין זמינים.', managementHistory: 'ניהול כללים והיסטוריה', refreshFailed: 'לא ניתן לרענן את העמידה בכללים', lastResultsVisible: 'התוצאות האחרונות שנטענו נשארו מוצגות.', rulesAndHistory: 'כללים והיסטוריה', recentLoadFailed: 'לא ניתן לטעון בדיקות אחרונות', adherenceRulesAvailable: 'העמידה והכללים עדיין זמינים.', adherenceManagement: 'עמידה וניהול כללים', rulesRefreshFailed: 'לא ניתן לרענן את הכללים', lastRulesVisible: 'הכללים האחרונים שנטענו נשארו מוצגים.', editingChecksAvailable: 'עריכה ותיעוד בדיקות', loadingRules: 'טוען כללים', rulesLoadFailed: 'לא ניתן לטעון את הכללים', rulesRequestFailed: 'הבקשה לכללים נכשלה.', adherenceHistory: 'עמידה והיסטוריית בדיקות', filteredEmpty: 'אין כללים התואמים למסננים הנוכחיים', clearRuleFiltersDetail: 'נקו את המסננים כדי לחזור לכל הכללים.', historicalChecks: 'בדיקה היסטורית אחת', historicalChecks_other: '{{count}} בדיקות היסטוריות', deactivate: 'השבתה', reactivate: 'הפעלה מחדש', historyRule: 'כלל בהיסטוריה', allRules: 'כל הכללים', historyOutcome: 'תוצאה בהיסטוריה', allOutcomes: 'כל התוצאות', historyRefreshFailed: 'לא ניתן לרענן את היסטוריית הבדיקות', lastChecksVisible: 'הבדיקות האחרונות שנטענו נשארו מוצגות.', adherenceAndRules: 'עמידה וכללים', loadingHistory: 'טוען היסטוריית בדיקות', historyLoadFailed: 'לא ניתן לטעון את היסטוריית הבדיקות', historyLoadFailedDetail: 'בקשת ההיסטוריה נכשלה. העמידה והכללים עדיין זמינים.', clearCheckFiltersDetail: 'נקו את המסננים כדי לחזור לכל הבדיקות בתקופה.',
  chooseRule: 'בחרו כלל.', chooseCheckDate: 'בחרו תאריך לבדיקה.', chooseOutcome: 'בחרו תוצאה.', scopeHelp: { trade: 'כלל לעסקה בדרך כלל מקושר לעסקה.', daily: 'כלל יומי בדרך כלל מקושר לסיכום יומי.', general: 'אפשר לתעד כלל כללי ללא קישור.' }, noLinkedTrade: 'ללא עסקה מקושרת', tradesLoadFailed: 'לא ניתן לטעון עסקאות. הבחירה הנוכחית נשמרה.', searchJournal: 'חיפוש רשומות ביומן', searchJournalPlaceholder: 'חיפוש בכותרת או בתוכן', availableJournal: 'רשומות יומן זמינות', noLinkedJournal: 'ללא רשומת יומן מקושרת', journalLoadFailed: 'לא ניתן לטעון רשומות יומן. הבחירה הנוכחית נשמרה.'
});

Object.assign(he.dailyReview, { metricsLoadFailed: 'לא ניתן לטעון את מדדי היום', tradesRulesReviewAvailable: 'העסקאות, הכללים והערות הסיכום עדיין זמינים.', tradesLoadFailed: 'לא ניתן לטעון את העסקאות', rulesReviewAvailable: 'עדיין אפשר לתעד כללים ולשמור את הסיכום.', noStrategyContext: 'ללא הקשר אסטרטגי', realizedUnavailable: 'רווח והפסד ממומש —', rulesLoadFailed: 'לא ניתן לטעון את הכללים', tradesReviewAvailable: 'העסקאות והסיכום היומי עדיין זמינים.', reviewLoadFailed: 'לא ניתן לטעון את הסיכום היומי', reviewLoadFailedDetail: 'מדדי היום, העסקאות והכללים עדיין זמינים. נסו שוב לפני עריכה כדי לא לדרוס תוכן שאינו ידוע.' });
Object.assign(he.analytics, { winsLosses: 'רווח / הפסד', refreshingDimension: 'מרענן ניתוח לפי ממד…', breakdownBy: 'פילוח ביצועים לפי', breakdownLoadFailed: 'לא ניתן לטעון את פילוח הביצועים', groupingUnavailable: 'הקיבוץ לפי {{dimension}} אינו זמין.', otherWidgetsAvailable: 'רכיבי לוח בקרה אחרים שנטענו ובקרי הפילוח', refreshingR: 'מרענן התפלגות R…', rBucketCounts: 'ספירות בטווחי מכפיל R', refreshingCalendar: 'מרענן את לוח השנה…', tradeSummary: '{{count}} עסקאות · אחוז הצלחה: {{rate}}', loadingBreakdown: 'טוען פילוח ביצועים', noBreakdown: 'עדיין אין פילוח לפי {{dimension}}', noBreakdownDetail: 'אין בטווח שנבחר עסקאות סגורות שאפשר לקבץ לתצוגה זו.', topGroups: '{{shown}} הקבוצות המובילות מתוך {{total}} לפי רווח והפסד נטו.', groupsInScope: 'קבוצה אחת בטווח.', groupsInScope_other: '{{count}} קבוצות בטווח.', netPnlChartLabel: 'תרשים רווח והפסד נטו עבור {{count}} קבוצות לפי {{dimension}}.' });
Object.assign(he.journal, { netPnlUnavailable: 'רווח והפסד נטו אינם זמינים', editNamed: 'עריכת {{title}}', deleteNamed: 'מחיקת {{title}}', pagination: 'דפדוף בציר הזמן של היומן' });
Object.assign(he.trades, { activeFilters: 'מסננים פעילים', loadingHeader: 'טוען כותרת טבלה', loadingRow: 'טוען שורת עסקה', filter: { from: 'מתאריך', to: 'עד תאריך', accountId: 'חשבון', symbol: 'סימול', market: 'שוק', direction: 'כיוון', status: 'סטטוס', outcome: 'תוצאה', strategy: 'אסטרטגיה', timeframe: 'טווח זמן' } });
Object.assign(he.trades, { notesPlaceholder: 'מחזור חזק בפריצה…' });
Object.assign(he.accounts, { numberPlaceholder: 'לדוגמה 12345678', namePlaceholder: 'לדוגמה ממומן ראשי' });
Object.assign(he.analytics, { increased: 'עלה', decreased: 'ירד', unchanged: 'נותר ללא שינוי', equityChartLabel: 'הרווח וההפסד הממומש המצטבר {{direction}} לאורך {{count}} ימים ומסתיים ב־{{value}}.', dailyNetPnl: 'רווח והפסד יומי נטו' });
Object.assign(he.goals, { metricHelp: { closed_trades: 'מספר העסקאות הסגורות.', win_rate: 'הגדרת אחוז ההצלחה הקיימת במוצר.', average_r: 'ממוצע ערכי R השמורים כאשר הם זמינים.', rule_adherence: 'בדיקות שבוצעו לפי הכלל חלקי בדיקות שבוצעו לפי הכלל ועוד הפרות.', journal_entries: 'מספר הרשומות ביומן.', broken_rule_checks: 'מספר ההפרות המרבי המותר.' } });
Object.assign(he.rules, { newRuleDialog: 'כלל מסחר חדש', editRuleDialog: 'עריכת כלל מסחר', recordCheckFormDialog: 'תיעוד בדיקת כלל', editCheckDialog: 'עריכת בדיקת כלל' });
Object.assign(he.journal, { daySummaryLabel: '{{date}}, רשומה אחת, {{complete}} הושלמו, {{incomplete}} לא הושלמו', daySummaryLabel_other: '{{date}}, {{total}} רשומות, {{complete}} הושלמו, {{incomplete}} לא הושלמו' });
Object.assign(he.analytics, { netPnlChartLabel: 'רווח והפסד נטו עבור קבוצה אחת לפי {{dimension}}.', netPnlChartLabel_other: 'רווח והפסד נטו עבור {{count}} קבוצות לפי {{dimension}}.', dimensionNames: { strategy: 'אסטרטגיה', symbol: 'סימול', timeframe: 'טווח זמן', direction: 'כיוון', account: 'חשבון', company: 'חברה', market: 'שוק', weekday: 'יום בשבוע', setup: 'סטאפ' } });
Object.assign(he.analytics, { dimensionChartLabel: 'תרשים רווח והפסד נטו עבור קבוצה אחת לפי {{dimension}}.', dimensionChartLabel_other: 'תרשים רווח והפסד נטו עבור {{count}} קבוצות לפי {{dimension}}.' });
Object.assign(he.common, { working: 'בביצוע' });
Object.assign(he.analytics, { loadingDimension: 'טוען ניתוח לפי ממד' });
Object.assign(he.dailyReview, { loadingMetric: 'טוען מדד יומי', loadingReview: 'טוען סיכום יומי' });
Object.assign(he.dailyReview, { emotionSuggestions: ['ממוקד', 'סבלני', 'בטוח', 'רגוע', 'לחוץ', 'מתוסכל', 'פחד מהחמצה'], mistakeSuggestions: ['מסחר יתר', 'רדיפה אחרי כניסה', 'הזזת סטופ', 'סיכון גדול מדי', 'עסקת נקמה', 'יציאה מוקדמת'] });
Object.assign(he.rules, { loadingPerRule: 'טוען עמידה לפי כלל', loadingRecent: 'טוען בדיקות אחרונות' });
Object.assign(he.trades, { loadingCard: 'טוען כרטיס עסקה' });
Object.assign(he.status, { stocks: 'מניות', crypto: 'קריפטו', futures: 'חוזים עתידיים', forex: 'פורקס' });
Object.assign(he.goals.metricHelp, { net_pnl: 'רווח והפסד נטו מעסקאות סגורות בתקופת היעד.' });
Object.assign(he.errors, { ACCOUNT_NOT_FOUND: 'החשבון לא נמצא.', EMAIL_IN_USE: 'כבר קיים חשבון עם כתובת האימייל הזו.', GOAL_NOT_FOUND: 'היעד לא נמצא.', INVALID_CREDENTIALS: 'כתובת האימייל או הסיסמה שגויות.', INVALID_FILE: 'הקובץ שנבחר אינו תקין.', INVALID_JOURNAL_LINK: 'רשומת היומן המקושרת אינה זמינה.', INVALID_REFRESH_TOKEN: 'פג תוקף החיבור. יש להתחבר מחדש.', INVALID_RULE_LINK: 'הכלל המקושר אינו זמין.', INVALID_TRADE_LINK: 'העסקה המקושרת אינה זמינה.', JOURNAL_ENTRY_NOT_FOUND: 'רשומת היומן לא נמצאה.', NO_REFRESH_TOKEN: 'פג תוקף החיבור. יש להתחבר מחדש.', RULE_CHECK_NOT_FOUND: 'בדיקת הכלל לא נמצאה.', RULE_HAS_CHECKS: 'אי אפשר למחוק כלל שיש לו בדיקות היסטוריות.', RULE_NOT_FOUND: 'הכלל לא נמצא.', SESSION_EXPIRED: 'פג תוקף החיבור. יש להתחבר מחדש.', TRADE_NOT_FOUND: 'העסקה לא נמצאה.', USER_NOT_FOUND: 'המשתמש לא נמצא.', VALIDATION_ERROR: 'יש לתקן את הערכים המסומנים.' });
Object.assign(he.auth, { namePlaceholder: 'דנה' });
Object.assign(he.validation, { numberRange: 'יש להזין ערך בין {{min}} ל־{{max}}.' });
Object.assign(he.goals, { targetWithUnit: 'יעד ({{unit}})', countUnit: 'כמות', nameRequired: 'יש להזין שם ליעד.', endDateOrder: 'תאריך הסיום אינו יכול להיות לפני תאריך ההתחלה.' });
Object.assign(he.rules, { nameRequired: 'יש להזין שם לכלל.' });

export default he;
