import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Plus } from '@phosphor-icons/react';
import { useTranslation } from 'react-i18next';
import { accountsApi } from '../api/accounts.js';
import { tradesApi } from '../api/trades.js';
import { AccountForm } from '../components/accounts/AccountForm.jsx';
import { Badge } from '../components/ui/Badge.jsx';
import { Button } from '../components/ui/Button.jsx';
import { Card } from '../components/ui/Card.jsx';
import { Modal } from '../components/ui/Modal.jsx';
import { EmptyState, ErrorState } from '../components/ui/States.jsx';
import { Skeleton } from '../components/ui/Skeleton.jsx';
import { useToast } from '../components/ui/Toast.jsx';
import { useDirection } from '../hooks/useDirection.js';
import { useUserTimezone } from '../hooks/useUserTimezone.js';
import { formatCurrency, formatDate, formatDatetime, formatNumber, formatPct, formatR, formatSignedCurrency } from '../utils/formatters.js';

export default function AccountDetail() {
  const { accountId } = useParams(); const { t } = useTranslation(); const { isRtl } = useDirection(); const timezone = useUserTimezone(); const navigate = useNavigate(); const qc = useQueryClient(); const toast = useToast(); const BackIcon = isRtl ? ArrowRight : ArrowLeft; const [editing, setEditing] = useState(false); const [confirmLifecycle, setConfirmLifecycle] = useState(false);
  const accountQuery = useQuery({ queryKey: ['account', accountId], queryFn: () => accountsApi.get(accountId), retry: false });
  const tradesQuery = useQuery({ queryKey: ['trades', { accountId, recent: true }], queryFn: () => tradesApi.list({ accountId, limit: 8, page: 1, sort: 'entry_datetime', order: 'desc' }), enabled: accountQuery.isSuccess });
  const mutation = useMutation({ mutationFn: data => accountsApi.update(accountId, data), onSuccess: () => { qc.invalidateQueries({ queryKey: ['accounts'] }); qc.invalidateQueries({ queryKey: ['account', accountId] }); setEditing(false); setConfirmLifecycle(false); toast.success(t('accounts.accountUpdated')); }, onError: e => toast.error(e.response?.data?.error?.message || t('accounts.saveFailed')) });
  if (accountQuery.isLoading) return <Skeleton className="h-96" label={t('accounts.loadingDetail')} />;
  if (accountQuery.isError) return accountQuery.error?.response?.status === 404 ? <EmptyState title={t('accounts.notFound')} detail={t('accounts.notFoundDetail')} action={<Button onClick={() => navigate('/accounts')}>{t('accounts.backToAccounts')}</Button>} /> : <ErrorState title={t('accounts.loadFailed')} detail={t('accounts.loadFailedDetail')} onRetry={accountQuery.refetch} />;
  const a = accountQuery.data; const currency = { currency: a.baseCurrency };
  const metric = (label, value) => <div><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 font-mono text-lg" dir="ltr">{value}</dd></div>;
  return <div className="space-y-5"><Button variant="tertiary" leadingIcon={<BackIcon size={16} aria-hidden="true" />} onClick={() => navigate('/accounts')}>{t('accounts.backToAccounts')}</Button>
    <Card><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-semibold text-primary" dir="auto">{a.accountName || a.company}</h2><p className="mt-1 text-sm text-secondary" dir="auto">{a.company}</p><p className="mt-1 font-mono text-sm" dir="ltr">{a.accountNumber}</p></div><div className="flex gap-2"><Badge>{t(`status.${a.status}`)}</Badge>{a.isDefault && <Badge variant="positive">{t('accounts.defaultAccount')}</Badge>}</div></div><dl className="mt-5 grid grid-cols-2 gap-4 adaptive:grid-cols-4">{metric(t('common.accountType'), a.accountType ? t(`status.${a.accountType}`) : '—')}{metric(t('accounts.baseCurrency'), a.baseCurrency)}{metric(t('accounts.lastTrade'), formatDate(a.lastTradeAt, { timezone }))}{metric(t('common.trades'), formatNumber(a.tradesCount))}</dl></Card>
    <section aria-labelledby="account-participation"><h2 id="account-participation" className="mb-3 text-sm font-semibold text-primary">{t('accounts.participation')}</h2><Card><div className="flex flex-wrap gap-2"><Badge>{t(`accounts.groups.${a.accountGroup}`)}</Badge><Badge variant={a.includeInInvestmentValue?'positive':'neutral'}>{t(a.includeInInvestmentValue?'accounts.includedInInvestments':'accounts.excludedFromInvestments')}</Badge><Badge variant={a.includeInNetWorth?'positive':'neutral'}>{t('accounts.personalNetWorth')}</Badge><Badge variant={a.includeInTradingAnalytics?'positive':'neutral'}>{t('accounts.tradingAnalytics')}</Badge></div>{a.linkedInvestmentPortfolio&&<div className="mt-4"><Link to={`/portfolio/${a.linkedInvestmentPortfolio.portfolioId}`} className="inline-flex min-h-11 items-center rounded-md border border-default px-3 text-sm font-medium text-action">{t('accounts.openInvestments')}</Link></div>}</Card></section>
    <section aria-labelledby="balance-context"><h2 id="balance-context" className="mb-3 text-sm font-semibold text-primary">{t('accounts.balanceContext')}</h2><Card><dl className="grid grid-cols-2 gap-4 adaptive:grid-cols-4">{metric(t('accounts.openingBalance'), formatCurrency(a.openingBalance, currency))}{metric(t('common.netPnl'), formatSignedCurrency(a.pnlNet, currency))}{metric(t('common.fees'), formatCurrency(a.totalFees, currency))}{metric(t('accounts.trackedBalance'), formatCurrency(a.trackedBalance, currency))}</dl><p className="mt-4 text-xs text-muted">{t('accounts.trackedBalanceExplanation')}</p></Card></section>
    <section aria-labelledby="account-performance"><h2 id="account-performance" className="mb-3 text-sm font-semibold text-primary">{t('accounts.performance')}</h2><Card><dl className="grid grid-cols-2 gap-4 adaptive:grid-cols-4 wide:grid-cols-8">{metric(t('accounts.closedTrades'), a.closedTrades)}{metric(t('accounts.openTrades'), a.openTrades)}{metric(t('accounts.winners'), a.winners)}{metric(t('accounts.losers'), a.losers)}{metric(t('common.breakeven'), a.breakeven)}{metric(t('common.winRate'), formatPct(a.winRate))}{metric(t('common.averageR'), formatR(a.averageR))}{metric(t('common.profitFactor'), a.profitFactor == null ? '—' : formatNumber(a.profitFactor, { maximumFractionDigits: 2 }))}</dl></Card></section>
    <section aria-labelledby="recent-trades"><div className="mb-3 flex items-center justify-between gap-3"><h2 id="recent-trades" className="text-sm font-semibold text-primary">{t('accounts.recentTrades')}</h2><Link to={`/trades?accountId=${encodeURIComponent(a.id)}`} className="inline-flex min-h-11 items-center rounded-md px-3 text-sm font-medium text-action hover:bg-action-soft">{t('accounts.viewAllTrades')}</Link></div>{tradesQuery.isLoading ? <Skeleton className="h-40" /> : tradesQuery.isError ? <ErrorState title={t('accounts.recentTradesFailed')} onRetry={tradesQuery.refetch} /> : !(tradesQuery.data?.data?.length) ? <EmptyState title={t('accounts.noTrades')} detail={t('accounts.noTradesDetail')} /> : <Card><ul className="divide-y divide-default">{tradesQuery.data.data.map(trade => <li key={trade.id}><Link to={`/trades/${trade.id}`} className="flex min-h-11 items-center justify-between gap-3 py-3"><span className="font-mono font-semibold" dir="ltr">{trade.symbol}</span><span className="text-xs text-muted" dir="ltr">{formatDatetime(trade.entryDatetime, { timezone })}</span><span className="font-mono text-sm" dir="ltr">{trade.pnlNet == null ? '—' : formatSignedCurrency(trade.pnlNet, currency)}</span></Link></li>)}</ul></Card>}</section>
    <div className="flex flex-wrap gap-2"><Button variant="primary" leadingIcon={<Plus size={16} aria-hidden="true" />} onClick={() => navigate(`/trades/new?accountId=${encodeURIComponent(a.id)}`)} disabled={a.status !== 'active'}>{t('accounts.createTrade')}</Button><Button variant="secondary" onClick={() => setEditing(true)}>{t('common.edit')}</Button>{a.status === 'active' && !a.isDefault && <Button variant="secondary" onClick={() => mutation.mutate({ isDefault: true })}>{t('accounts.setDefault')}</Button>}<Button variant="secondary" onClick={() => setConfirmLifecycle(true)}>{t(a.status === 'archived' ? 'accounts.restore' : 'accounts.archive')}</Button></div>
    <Modal open={editing} onClose={() => !mutation.isPending && setEditing(false)} title={t('accounts.editAccount')} size="md"><AccountForm account={a} loading={mutation.isPending} onSubmit={data => mutation.mutate(data)} /></Modal>
    <Modal open={confirmLifecycle} onClose={() => !mutation.isPending && setConfirmLifecycle(false)} title={t('accounts.confirmLifecycle')} size="sm"><div className="space-y-4"><p className="text-sm text-secondary">{t(a.status === 'archived' ? 'accounts.restoreConfirm' : 'accounts.archiveConfirm', { name: a.accountName || a.company })}</p><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setConfirmLifecycle(false)}>{t('common.cancel')}</Button><Button variant="primary" disabled={mutation.isPending} onClick={() => mutation.mutate({ status: a.status === 'archived' ? 'active' : 'archived' })}>{t('common.update')}</Button></div></div></Modal>
  </div>;
}
