import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Archive, ArrowCounterClockwise, ArrowLeft, ArrowRight, CurrencyDollar, PencilSimple, Plus } from '@phosphor-icons/react';
import { useTranslation } from 'react-i18next';
import { portfolioApi } from '../api/portfolio.js';
import { InvestmentInstrumentForm } from '../components/portfolio/InvestmentInstrumentForm.jsx';
import { ManualPriceForm } from '../components/portfolio/ManualPriceForm.jsx';
import { PortfolioForm } from '../components/portfolio/PortfolioForm.jsx';
import { PortfolioTransactionForm } from '../components/portfolio/PortfolioTransactionForm.jsx';
import { invalidateInvestmentWorkspace } from '../components/portfolio/investmentQueryInvalidation.js';
import { Badge } from '../components/ui/Badge.jsx';
import { Button } from '../components/ui/Button.jsx';
import { Card } from '../components/ui/Card.jsx';
import { EmptyState, ErrorState } from '../components/ui/States.jsx';
import { Modal } from '../components/ui/Modal.jsx';
import { Skeleton } from '../components/ui/Skeleton.jsx';
import { useToast } from '../components/ui/Toast.jsx';
import { useDirection } from '../hooks/useDirection.js';
import { formatCurrency, formatDate, formatNumber, formatPct, formatSignedCurrency } from '../utils/formatters.js';

function money(value,currency,signed=false){return value==null?'—':(signed?formatSignedCurrency(value,{currency}):formatCurrency(value,{currency}));}
function localizedError(t,error,fallbackKey='portfolio.saveFailed'){const code=error.response?.data?.error?.code;return code?t(`portfolio.errors.${code}`,{defaultValue:t(fallbackKey)}):t(fallbackKey);}
function Metric({label,value,muted=false}){return <div><dt className="text-xs text-muted">{label}</dt><dd className={`mt-1 whitespace-nowrap font-mono text-lg font-semibold ${muted?'text-muted':'text-primary'}`} dir="ltr">{value}</dd></div>}
function PositionCard({position,currency,onPrice}){const{t}=useTranslation();return <Card density="compact"><div className="flex items-start justify-between gap-3"><div><strong className="font-mono text-primary" dir="ltr">{position.symbol}</strong><p className="text-xs text-muted" dir="auto">{position.name||t(`portfolio.assetTypes.${position.assetType}`)}</p></div><Badge>{t(`portfolio.assetTypes.${position.assetType}`)}</Badge></div><dl className="mt-4 grid grid-cols-2 gap-3"><Metric label={t('common.quantity')} value={formatNumber(position.quantity,{maximumFractionDigits:8})}/><Metric label={t('portfolio.averageCost')} value={money(position.averageCost,currency)}/><Metric label={t('portfolio.costBasis')} value={money(position.costBasis,currency)}/><Metric label={t('portfolio.manualPrice')} value={money(position.latestPrice,currency)} muted={!position.valuationAvailable}/><Metric label={t('portfolio.marketValue')} value={money(position.marketValue,currency)} muted={!position.valuationAvailable}/><Metric label={t('portfolio.unrealizedPnl')} value={money(position.unrealizedPnl,currency,true)} muted={!position.valuationAvailable}/><Metric label={t('portfolio.unrealizedReturn')} value={formatPct(position.unrealizedReturnPercent)} muted={!position.valuationAvailable}/><Metric label={t('portfolio.dividendIncome')} value={money(position.dividendIncome,currency)}/></dl><div className="mt-3 flex items-center justify-between border-t border-default pt-3"><span className="text-xs text-muted">{t('portfolio.priceDate')}: <span dir="ltr">{formatDate(position.latestPriceDate)}</span></span><Button size="sm" variant="tertiary" onClick={()=>onPrice(position.instrumentId)}>{t('portfolio.updatePrice')}</Button></div></Card>}

function TransactionRow({item,onEdit,onDelete}){const{t}=useTranslation();const value=item.quantity!=null?`${formatNumber(item.quantity,{maximumFractionDigits:8})} × ${money(item.price,item.currency)}`:money(item.amount,item.currency);return <tr className="border-b border-default"><td className="px-3 py-3" dir="ltr">{formatDate(item.transactionDate)}</td><td className="px-3 py-3"><Badge>{t(`portfolio.transactionTypes.${item.transactionType}`)}</Badge></td><td className="px-3 py-3 font-mono" dir="ltr">{item.instrumentSymbol||'—'}</td><td className="px-3 py-3 text-end font-mono" dir="ltr">{value}</td><td className="px-3 py-3 text-end font-mono" dir="ltr">{money(item.fees,item.currency)}</td><td className="max-w-48 truncate px-3 py-3" dir="auto">{item.notes||'—'}</td><td className="px-3 py-3"><div className="flex justify-end gap-1"><Button size="sm" variant="tertiary" onClick={()=>onEdit(item)}>{t('common.edit')}</Button><Button size="sm" variant="tertiary" onClick={()=>onDelete(item)}>{t('common.delete')}</Button></div></td></tr>}

export default function PortfolioDetail(){const{portfolioId}=useParams();const{t}=useTranslation();const{isRtl}=useDirection();const navigate=useNavigate();const qc=useQueryClient();const toast=useToast();const BackIcon=isRtl?ArrowRight:ArrowLeft;const[portfolioForm,setPortfolioForm]=useState(false);const[instrumentForm,setInstrumentForm]=useState(null);const[transactionForm,setTransactionForm]=useState(null);const[priceInstrument,setPriceInstrument]=useState(null);const[deleteTarget,setDeleteTarget]=useState(null);const[lifecycle,setLifecycle]=useState(false);
  const portfolioQuery=useQuery({queryKey:['portfolio',portfolioId],queryFn:()=>portfolioApi.get(portfolioId),retry:false});const instrumentsQuery=useQuery({queryKey:['investment-instruments',{includeInactive:true}],queryFn:()=>portfolioApi.instruments({includeInactive:'true'})});const invalidate=()=>{invalidateInvestmentWorkspace(qc,{transaction:true,price:true});qc.invalidateQueries({queryKey:['portfolio',portfolioId]});qc.invalidateQueries({queryKey:['investment-instruments']});};
  const portfolioMutation=useMutation({mutationFn:(data)=>portfolioApi.update(portfolioId,data),onSuccess:()=>{invalidate();setPortfolioForm(false);setLifecycle(false);toast.success(t('portfolio.saved'));},onError:(error)=>toast.error(localizedError(t,error))});
  const instrumentMutation=useMutation({mutationFn:({id,data})=>id?portfolioApi.updateInstrument(id,data):portfolioApi.createInstrument(data),onSuccess:()=>{invalidate();setInstrumentForm(null);toast.success(t('portfolio.instrumentSaved'));},onError:(error)=>toast.error(localizedError(t,error))});
  const transactionMutation=useMutation({mutationFn:({id,data})=>id?portfolioApi.updateTransaction(id,data):portfolioApi.createTransaction(data),onSuccess:()=>{invalidate();setTransactionForm(null);toast.success(t('portfolio.transactionSaved'));},onError:(error)=>toast.error(localizedError(t,error))});
  const deleteMutation=useMutation({mutationFn:(id)=>portfolioApi.deleteTransaction(id),onSuccess:()=>{invalidate();setDeleteTarget(null);toast.success(t('portfolio.transactionDeleted'));},onError:(error)=>toast.error(localizedError(t,error,'portfolio.deleteFailed'))});
  const priceMutation=useMutation({mutationFn:({instrumentId,date,data})=>portfolioApi.upsertPrice(instrumentId,date,data),onSuccess:()=>{invalidate();setPriceInstrument(null);toast.success(t('portfolio.priceSaved'));},onError:(error)=>toast.error(localizedError(t,error))});
  if(portfolioQuery.isLoading)return <Skeleton className="h-96" label={t('portfolio.loadingDetail')}/>;
  if(portfolioQuery.isError)return portfolioQuery.error?.response?.status===404?<EmptyState title={t('portfolio.notFound')} detail={t('portfolio.notFoundDetail')} action={<Button onClick={()=>navigate('/portfolio')}>{t('portfolio.back')}</Button>}/>:<ErrorState title={t('portfolio.loadFailed')} onRetry={portfolioQuery.refetch}/>;
  const loadedPortfolio=portfolioQuery.data.portfolio;const linkedAccount=loadedPortfolio.tradingAccount;const p=linkedAccount&&linkedAccount.status!=='active'?{...loadedPortfolio,status:'archived'}:loadedPortfolio;const instruments=instrumentsQuery.data?.instruments||[];const portfolioInstruments=instruments.filter((item)=>item.currency===p.baseCurrency);const activeInstruments=portfolioInstruments.filter((item)=>item.isActive);const transactions=p.recentTransactions||[];
  return <div className="space-y-5"><Button variant="tertiary" leadingIcon={<BackIcon size={16} aria-hidden="true"/>} onClick={()=>navigate('/portfolio')}>{t('portfolio.back')}</Button>
    <Card><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-semibold text-primary" dir="auto">{linkedAccount?.accountName||linkedAccount?.company||p.name}</h2>{linkedAccount?<><p className="mt-1 text-sm text-secondary" dir="auto">{linkedAccount.company}</p><p className="mt-1 font-mono text-xs text-muted" dir="ltr">{linkedAccount.accountNumber}</p></>:p.description&&<p className="mt-1 text-sm text-secondary" dir="auto">{p.description}</p>}<div className="mt-2 flex gap-2"><Badge variant={(linkedAccount?.status||p.status)==='active'?'positive':'neutral'}>{t(`status.${linkedAccount?.status||p.status}`)}</Badge>{linkedAccount&&<Badge>{t('portfolio.investmentAccount')}</Badge>}<Badge><span dir="ltr">{p.baseCurrency}</span></Badge></div></div>{linkedAccount?<Link to={`/accounts/${linkedAccount.id}`} className="inline-flex min-h-11 items-center rounded-md border border-default px-3 text-sm font-medium text-action">{t('portfolio.viewAccount')}</Link>:<div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" leadingIcon={<PencilSimple size={15} aria-hidden="true"/>} onClick={()=>setPortfolioForm(true)}>{t('common.edit')}</Button>{p.status==='active'&&!p.isDefault&&<Button size="sm" onClick={()=>portfolioMutation.mutate({isDefault:true})}>{t('portfolio.setDefault')}</Button>}<Button size="sm" variant="secondary" leadingIcon={p.status==='active'?<Archive size={15} aria-hidden="true"/>:<ArrowCounterClockwise size={15} aria-hidden="true"/>} onClick={()=>setLifecycle(true)}>{t(p.status==='active'?'portfolio.archive':'portfolio.restore')}</Button></div>}</div></Card>
    {!p.valuationAvailable&&<section className="rounded-lg border border-warning bg-warning-soft p-4" role="status"><h2 className="font-semibold text-primary">{t('portfolio.valuationUnavailable')}</h2><p className="mt-1 text-sm text-secondary">{t('portfolio.valuationUnavailableDetail',{count:p.missingPriceCount})}</p></section>}
    <section aria-labelledby="portfolio-detail-summary"><h2 id="portfolio-detail-summary" className="mb-3 text-sm font-semibold text-primary">{t('portfolio.summary')}</h2><Card><dl className="grid grid-cols-2 gap-4 adaptive:grid-cols-4 wide:grid-cols-5"><Metric label={t('portfolio.cashBalance')} value={money(p.cashBalance,p.baseCurrency)}/><Metric label={t('portfolio.netContributions')} value={money(p.netContributions,p.baseCurrency)}/><Metric label={t('portfolio.costBasis')} value={money(p.totalCostBasis,p.baseCurrency)}/><Metric label={t('portfolio.marketValue')} value={money(p.marketValue,p.baseCurrency)} muted={!p.valuationAvailable}/><Metric label={t('portfolio.totalValue')} value={money(p.totalValue,p.baseCurrency)} muted={!p.valuationAvailable}/><Metric label={t('portfolio.realizedPnl')} value={money(p.realizedPnl,p.baseCurrency,true)}/><Metric label={t('portfolio.unrealizedPnl')} value={money(p.unrealizedPnl,p.baseCurrency,true)} muted={!p.valuationAvailable}/><Metric label={t('portfolio.dividendIncome')} value={money(p.dividendIncome,p.baseCurrency)}/><Metric label={t('common.fees')} value={money(p.totalFees,p.baseCurrency)}/><Metric label={t('portfolio.totalReturn')} value={money(p.totalReturn,p.baseCurrency,true)} muted={!p.valuationAvailable}/></dl><p className="mt-4 text-xs text-muted">{t('portfolio.accountingBoundary')}</p></Card></section>
    <section aria-labelledby="positions-heading"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h2 id="positions-heading" className="text-sm font-semibold text-primary">{t('portfolio.positions')}</h2><div className="flex flex-wrap gap-2"><Button size="sm" leadingIcon={<Plus size={14} aria-hidden="true"/>} onClick={()=>setInstrumentForm({})}>{t('portfolio.addInstrument')}</Button><Button size="sm" leadingIcon={<CurrencyDollar size={14} aria-hidden="true"/>} disabled={!portfolioInstruments.length} onClick={()=>setPriceInstrument('')}>{t('portfolio.updatePrice')}</Button></div></div>
    {!p.positions.length?<EmptyState title={t('portfolio.noPositions')} detail={t('portfolio.noPositionsDetail')}/>:<><div className="grid gap-3 adaptive:hidden">{p.positions.map((position)=><PositionCard key={position.instrumentId} position={position} currency={p.baseCurrency} onPrice={setPriceInstrument}/>)}</div><Card className="hidden overflow-x-auto p-0 adaptive:block"><table className="w-full min-w-[850px] text-sm"><thead className="bg-surface-raised text-xs text-muted"><tr>{['instrument','quantity','averageCost','costBasis','manualPrice','marketValue','unrealizedPnl','unrealizedReturn','dividendIncome'].map((key)=><th key={key} scope="col" className="px-3 py-2 text-start">{t(`portfolio.${key}`)}</th>)}</tr></thead><tbody>{p.positions.map((position)=><tr key={position.instrumentId} className="border-t border-default"><td className="px-3 py-3"><span className="block font-mono font-semibold" dir="ltr">{position.symbol}</span><span className="block text-xs text-muted" dir="auto">{position.name}</span></td><td className="px-3 py-3 font-mono" dir="ltr">{formatNumber(position.quantity,{maximumFractionDigits:8})}</td><td className="px-3 py-3 font-mono" dir="ltr">{money(position.averageCost,p.baseCurrency)}</td><td className="px-3 py-3 font-mono" dir="ltr">{money(position.costBasis,p.baseCurrency)}</td><td className="px-3 py-3"><button type="button" className="min-h-11 font-mono text-action" dir="ltr" onClick={()=>setPriceInstrument(position.instrumentId)}>{money(position.latestPrice,p.baseCurrency)}</button><span className="block text-xs text-muted" dir="ltr">{formatDate(position.latestPriceDate)}</span></td><td className="px-3 py-3 font-mono" dir="ltr">{money(position.marketValue,p.baseCurrency)}</td><td className="px-3 py-3 font-mono" dir="ltr">{money(position.unrealizedPnl,p.baseCurrency,true)}</td><td className="px-3 py-3 font-mono" dir="ltr">{formatPct(position.unrealizedReturnPercent)}</td><td className="px-3 py-3 font-mono" dir="ltr">{money(position.dividendIncome,p.baseCurrency)}</td></tr>)}</tbody></table></Card></>}
    </section>
    <section aria-labelledby="instruments-heading"><h2 id="instruments-heading" className="mb-3 text-sm font-semibold text-primary">{t('portfolio.instrumentLibrary')}</h2>{!portfolioInstruments.length?<EmptyState title={t('portfolio.noInstruments')} detail={t('portfolio.noInstrumentsDetail')}/>:<div className="grid gap-3 adaptive:grid-cols-2 wide:grid-cols-3">{portfolioInstruments.map((item)=><Card key={item.id} density="compact"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><strong className="font-mono text-primary" dir="ltr">{item.symbol}</strong><p className="truncate text-sm text-secondary" dir="auto">{item.name||t(`portfolio.assetTypes.${item.assetType}`)}</p><p className="text-xs text-muted" dir="ltr">{item.exchange||'—'} · {item.currency}</p></div><Badge variant={item.isActive?'positive':'neutral'}>{t(item.isActive?'common.active':'common.inactive')}</Badge></div><div className="mt-3 flex justify-end gap-2 border-t border-default pt-3"><Button size="sm" onClick={()=>setInstrumentForm(item)}>{t('common.edit')}</Button><Button size="sm" variant="tertiary" loading={instrumentMutation.isPending&&instrumentMutation.variables?.id===item.id} onClick={()=>instrumentMutation.mutate({id:item.id,data:{isActive:!item.isActive}})}>{t(item.isActive?'portfolio.deactivateInstrument':'portfolio.reactivateInstrument')}</Button></div></Card>)}</div>}</section>
    <section aria-labelledby="transactions-heading"><div className="mb-3 flex items-center justify-between gap-3"><h2 id="transactions-heading" className="text-sm font-semibold text-primary">{t('portfolio.transactions')}</h2><Button variant="primary" size="mobile" leadingIcon={<Plus size={15} aria-hidden="true"/>} disabled={p.status!=='active'||instrumentsQuery.isError} onClick={()=>setTransactionForm({})}>{t('portfolio.addTransaction')}</Button></div>{instrumentsQuery.isError&&<ErrorState title={t('portfolio.instrumentsLoadFailed')} onRetry={instrumentsQuery.refetch}/>} {!transactions.length?<EmptyState title={t('portfolio.noTransactions')} detail={t('portfolio.noTransactionsDetail')}/>:<><div className="grid gap-3 adaptive:hidden">{transactions.map((item)=><Card key={item.id} density="compact"><div className="flex items-start justify-between"><div><Badge>{t(`portfolio.transactionTypes.${item.transactionType}`)}</Badge><p className="mt-2 font-mono font-semibold" dir="ltr">{item.instrumentSymbol||item.currency}</p></div><span className="text-xs text-muted" dir="ltr">{formatDate(item.transactionDate)}</span></div><dl className="mt-3 grid grid-cols-2 gap-3"><Metric label={t('portfolio.value')} value={item.quantity!=null?`${formatNumber(item.quantity)} × ${money(item.price,item.currency)}`:money(item.amount,item.currency)}/><Metric label={t('common.fees')} value={money(item.fees,item.currency)}/></dl>{item.notes&&<p className="mt-3 text-sm text-secondary" dir="auto">{item.notes}</p>}<div className="mt-3 flex justify-end gap-2"><Button size="sm" onClick={()=>setTransactionForm(item)}>{t('common.edit')}</Button><Button size="sm" variant="destructive" onClick={()=>setDeleteTarget(item)}>{t('common.delete')}</Button></div></Card>)}</div><Card className="hidden overflow-x-auto p-0 adaptive:block"><table className="w-full min-w-[800px] text-sm"><thead className="bg-surface-raised text-xs text-muted"><tr><th className="px-3 py-2 text-start">{t('common.date')}</th><th className="px-3 py-2 text-start">{t('common.type')}</th><th className="px-3 py-2 text-start">{t('portfolio.instrument')}</th><th className="px-3 py-2 text-end">{t('portfolio.value')}</th><th className="px-3 py-2 text-end">{t('common.fees')}</th><th className="px-3 py-2 text-start">{t('common.notes')}</th><th className="px-3 py-2 text-end">{t('common.actions')}</th></tr></thead><tbody>{transactions.map((item)=><TransactionRow key={item.id} item={item} onEdit={setTransactionForm} onDelete={setDeleteTarget}/>)}</tbody></table></Card></>}</section>
    <Modal open={portfolioForm} onClose={()=>!portfolioMutation.isPending&&setPortfolioForm(false)} title={t('portfolio.editPortfolio')}><PortfolioForm portfolio={p} loading={portfolioMutation.isPending} onSubmit={(data)=>portfolioMutation.mutate(data)}/></Modal>
    <Modal open={instrumentForm!==null} onClose={()=>!instrumentMutation.isPending&&setInstrumentForm(null)} title={t(instrumentForm?.id?'portfolio.editInstrument':'portfolio.addInstrument')}><InvestmentInstrumentForm key={instrumentForm?.id||'new'} instrument={instrumentForm?.id?instrumentForm:null} portfolioCurrency={p.baseCurrency} loading={instrumentMutation.isPending} onSubmit={(data)=>instrumentMutation.mutate({id:instrumentForm?.id,data})}/></Modal>
    <Modal open={transactionForm!==null} onClose={()=>!transactionMutation.isPending&&setTransactionForm(null)} title={transactionForm?.id?t('portfolio.editTransaction'):t('portfolio.addTransaction')} size="lg"><PortfolioTransactionForm key={transactionForm?.id||'new'} portfolio={p} instruments={activeInstruments.concat(instruments.filter((item)=>item.id===transactionForm?.instrumentId&&!item.isActive))} transaction={transactionForm?.id?transactionForm:null} loading={transactionMutation.isPending} onSubmit={(data)=>transactionMutation.mutate({id:transactionForm?.id,data:transactionForm?.id?Object.fromEntries(Object.entries(data).filter(([key])=>key!=='portfolioId')):data})}/></Modal>
    <Modal open={priceInstrument!==null} onClose={()=>!priceMutation.isPending&&setPriceInstrument(null)} title={t('portfolio.updateManualPrice')}><ManualPriceForm key={priceInstrument||'choose'} instruments={portfolioInstruments} initialInstrumentId={priceInstrument||''} loading={priceMutation.isPending} onSubmit={(data)=>priceMutation.mutate(data)}/></Modal>
    <Modal open={deleteTarget!==null} onClose={()=>!deleteMutation.isPending&&setDeleteTarget(null)} title={t('portfolio.deleteTransaction')} size="sm"><p className="text-sm text-secondary">{t('portfolio.deleteConfirm')}</p><div className="mt-4 flex justify-end gap-2"><Button onClick={()=>setDeleteTarget(null)}>{t('common.cancel')}</Button><Button variant="destructive" loading={deleteMutation.isPending} onClick={()=>deleteMutation.mutate(deleteTarget.id)}>{t('common.delete')}</Button></div></Modal>
    <Modal open={lifecycle} onClose={()=>!portfolioMutation.isPending&&setLifecycle(false)} title={t(p.status==='active'?'portfolio.archive':'portfolio.restore')} size="sm"><p className="text-sm text-secondary">{t(p.status==='active'?'portfolio.archiveConfirm':'portfolio.restoreConfirm',{name:p.name})}</p><div className="mt-4 flex justify-end gap-2"><Button onClick={()=>setLifecycle(false)}>{t('common.cancel')}</Button><Button variant="primary" loading={portfolioMutation.isPending} onClick={()=>portfolioMutation.mutate({status:p.status==='active'?'archived':'active'})}>{t('common.update')}</Button></div></Modal>
  </div>;
}
