import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Archive, ArrowCounterClockwise, PencilSimple, Plus } from '@phosphor-icons/react';
import { useTranslation } from 'react-i18next';
import { portfolioApi } from '../api/portfolio.js';
import { PortfolioForm } from '../components/portfolio/PortfolioForm.jsx';
import { Badge } from '../components/ui/Badge.jsx';
import { Button } from '../components/ui/Button.jsx';
import { Card } from '../components/ui/Card.jsx';
import { EmptyState, ErrorState } from '../components/ui/States.jsx';
import { Modal } from '../components/ui/Modal.jsx';
import { Skeleton } from '../components/ui/Skeleton.jsx';
import { useToast } from '../components/ui/Toast.jsx';
import { formatCurrency, formatDate, formatNumber, formatSignedCurrency } from '../utils/formatters.js';

function money(value, currency, signed=false){return value==null?'—':(signed?formatSignedCurrency(value,{currency}):formatCurrency(value,{currency}));}
function Metric({label,value,dir='ltr'}){return <div><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 whitespace-nowrap font-mono text-lg font-semibold text-primary" dir={dir}>{value}</dd></div>}

function PortfolioCard({item,onEdit,onLifecycle,onDefault,pending}){const{t}=useTranslation();return <Card as="article"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><Link to={`/portfolio/${item.id}`} className="text-base font-semibold text-primary hover:text-action" dir="auto">{item.name}</Link>{item.description&&<p className="mt-1 line-clamp-2 text-sm text-secondary" dir="auto">{item.description}</p>}<div className="mt-2 flex flex-wrap gap-2"><Badge variant={item.status==='active'?'positive':'neutral'}>{t(`status.${item.status}`)}</Badge>{item.isDefault&&<Badge variant="info">{t('portfolio.defaultPortfolio')}</Badge>}<Badge><span dir="ltr">{item.baseCurrency}</span></Badge></div></div><div className="flex gap-1"><Button size="sm" variant="tertiary" onClick={()=>onEdit(item)} aria-label={t('portfolio.editNamed',{name:item.name})}><PencilSimple size={16} aria-hidden="true" /></Button><Button size="sm" variant="tertiary" loading={pending} onClick={()=>onLifecycle(item)} aria-label={t(item.status==='active'?'portfolio.archive':'portfolio.restore')} >{item.status==='active'?<Archive size={16} aria-hidden="true"/>:<ArrowCounterClockwise size={16} aria-hidden="true"/>}</Button></div></div>
  <dl className="mt-5 grid grid-cols-2 gap-4 adaptive:grid-cols-3"><Metric label={t('portfolio.positions')} value={formatNumber(item.positionCount)}/><Metric label={t('portfolio.cashBalance')} value={money(item.cashBalance,item.baseCurrency)}/><Metric label={t('portfolio.marketValue')} value={item.valuationAvailable?money(item.marketValue,item.baseCurrency):'—'}/><Metric label={t('portfolio.totalValue')} value={item.valuationAvailable?money(item.totalValue,item.baseCurrency):'—'}/><Metric label={t('portfolio.realizedPnl')} value={money(item.realizedPnl,item.baseCurrency,true)}/><Metric label={t('portfolio.unrealizedPnl')} value={item.valuationAvailable?money(item.unrealizedPnl,item.baseCurrency,true):'—'}/><Metric label={t('portfolio.dividendIncome')} value={money(item.dividendIncome,item.baseCurrency)}/></dl>
  {!item.valuationAvailable&&<p className="mt-4 rounded-md bg-warning-soft p-2 text-xs text-secondary" role="status">{t('portfolio.missingPriceCount',{count:item.missingPriceCount})}</p>}
  <div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-default pt-3"><span className="text-xs text-muted">{t('portfolio.lastTransaction')}: <span dir="ltr">{formatDate(item.lastTransactionDate)}</span></span><div className="flex gap-2">{item.status==='active'&&!item.isDefault&&<Button size="sm" onClick={()=>onDefault(item)}>{t('portfolio.setDefault')}</Button>}<Link to={`/portfolio/${item.id}`} className="inline-flex min-h-8 items-center justify-center rounded-md border border-strong bg-surface-raised px-3 py-1 text-xs font-medium text-primary hover:bg-surface-sunken">{t('common.view')}</Link></div></div></Card>}

export default function Portfolio(){const{t}=useTranslation();const qc=useQueryClient();const toast=useToast();const[form,setForm]=useState(null);const[confirm,setConfirm]=useState(null);const query=useQuery({queryKey:['portfolios',{includeArchived:true}],queryFn:()=>portfolioApi.list({includeArchived:'true'})});const mutation=useMutation({mutationFn:({id,data})=>id?portfolioApi.update(id,data):portfolioApi.create(data),onSuccess:()=>{qc.invalidateQueries({queryKey:['portfolios']});setForm(null);setConfirm(null);toast.success(t('portfolio.saved'));},onError:(error)=>toast.error(error.response?.data?.error?.code==='PORTFOLIO_NAME_EXISTS'?t('portfolio.duplicate'):t('portfolio.saveFailed'))});const portfolios=query.data?.portfolios||[];const active=portfolios.filter((item)=>item.status==='active');const archived=portfolios.filter((item)=>item.status==='archived');const grouped=useMemo(()=>{const map=new Map();for(const item of active){const group=map.get(item.baseCurrency)||{currency:item.baseCurrency,netContributions:0,totalValue:0,realizedPnl:0,dividendIncome:0,valuationAvailable:true};group.netContributions+=item.netContributions;group.realizedPnl+=item.realizedPnl;group.dividendIncome+=item.dividendIncome;if(item.valuationAvailable)group.totalValue+=item.totalValue;else group.valuationAvailable=false;map.set(item.baseCurrency,group);}return [...map.values()];},[active]);
  if(query.isLoading)return <div className="space-y-4"><Skeleton className="h-24" label={t('portfolio.loading')}/><Skeleton className="h-64" label={t('portfolio.loading')}/></div>;
  if(query.isError)return <ErrorState title={t('portfolio.loadFailed')} detail={t('portfolio.loadFailedDetail')} onRetry={query.refetch}/>;
  return <div className="space-y-5"><div className="flex justify-end"><Button variant="primary" size="mobile" leadingIcon={<Plus size={16} aria-hidden="true"/>} onClick={()=>setForm({})}>{t('portfolio.createPortfolio')}</Button></div>
    <section aria-labelledby="portfolio-summary"><h2 id="portfolio-summary" className="sr-only">{t('portfolio.summary')}</h2><dl className="grid grid-cols-2 gap-3 adaptive:grid-cols-4"><Card as="div" density="compact"><Metric label={t('portfolio.activePortfolios')} value={formatNumber(active.length)}/></Card><Card as="div" density="compact"><Metric label={t('portfolio.archivedPortfolios')} value={formatNumber(archived.length)}/></Card><Card as="div" density="compact"><Metric label={t('portfolio.totalPositions')} value={formatNumber(active.reduce((sum,item)=>sum+item.positionCount,0))}/></Card><Card as="div" density="compact"><Metric label={t('portfolio.defaultPortfolio')} value={active.find((item)=>item.isDefault)?.name||t('common.none')} dir="auto"/></Card></dl>
    <div className="mt-3 grid gap-3 adaptive:grid-cols-2">{grouped.map((group)=><Card key={group.currency} density="compact"><div className="flex items-center justify-between"><h3 className="font-semibold text-primary" dir="ltr">{group.currency}</h3>{grouped.length>1&&<Badge>{t('portfolio.noFxConversion')}</Badge>}</div><dl className="mt-3 grid grid-cols-2 gap-3"><Metric label={t('portfolio.netContributions')} value={money(group.netContributions,group.currency)}/><Metric label={t('portfolio.totalValue')} value={group.valuationAvailable?money(group.totalValue,group.currency):'—'}/><Metric label={t('portfolio.realizedPnl')} value={money(group.realizedPnl,group.currency,true)}/><Metric label={t('portfolio.dividendIncome')} value={money(group.dividendIncome,group.currency)}/></dl>{!group.valuationAvailable&&<p className="mt-3 text-xs text-warning">{t('portfolio.totalUnavailable')}</p>}</Card>)}</div></section>
    {!portfolios.length?<EmptyState title={t('portfolio.empty')} detail={t('portfolio.emptyDetail')} action={<Button variant="primary" onClick={()=>setForm({})}>{t('portfolio.createPortfolio')}</Button>}/>:<><section aria-labelledby="active-portfolios"><h2 id="active-portfolios" className="mb-3 text-sm font-semibold text-primary">{t('portfolio.activePortfolios')}</h2><div className="grid gap-4 wide:grid-cols-2">{active.map((item)=><PortfolioCard key={item.id} item={item} onEdit={setForm} onLifecycle={setConfirm} onDefault={(value)=>mutation.mutate({id:value.id,data:{isDefault:true}})} pending={mutation.isPending&&mutation.variables?.id===item.id}/>)}</div></section>{archived.length>0&&<section aria-labelledby="archived-portfolios"><h2 id="archived-portfolios" className="mb-3 text-sm font-semibold text-primary">{t('portfolio.archivedPortfolios')}</h2><div className="grid gap-4 wide:grid-cols-2">{archived.map((item)=><PortfolioCard key={item.id} item={item} onEdit={setForm} onLifecycle={setConfirm} onDefault={()=>{}} pending={mutation.isPending&&mutation.variables?.id===item.id}/>)}</div></section>}</>}
    <Modal open={form!==null} onClose={()=>!mutation.isPending&&setForm(null)} title={form?.id?t('portfolio.editPortfolio'):t('portfolio.createPortfolio')}><PortfolioForm key={form?.id||'new'} portfolio={form?.id?form:null} loading={mutation.isPending} onSubmit={(data)=>mutation.mutate({id:form?.id,data})}/></Modal>
    <Modal open={confirm!==null} onClose={()=>!mutation.isPending&&setConfirm(null)} title={t(confirm?.status==='active'?'portfolio.archive':'portfolio.restore')} size="sm"><p className="text-sm text-secondary">{t(confirm?.status==='active'?'portfolio.archiveConfirm':'portfolio.restoreConfirm',{name:confirm?.name})}</p><div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setConfirm(null)}>{t('common.cancel')}</Button><Button variant="primary" loading={mutation.isPending} onClick={()=>mutation.mutate({id:confirm.id,data:{status:confirm.status==='active'?'archived':'active'}})}>{t('common.update')}</Button></div></Modal>
  </div>;
}
