import { useId, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Button } from '../ui/Button.jsx';
import { Field, Input, Select } from '../ui/FormControls.jsx';
import { currentDateKey } from '../../utils/dateOnly.js';
import { useUserTimezone } from '../../hooks/useUserTimezone.js';

const TYPES=['buy','sell','dividend','fee','deposit','withdrawal'];
export function normalizePortfolioTransaction(form, portfolioId){const market=['buy','sell'].includes(form.transactionType);const amount=['dividend','fee','deposit','withdrawal'].includes(form.transactionType);return {portfolioId,instrumentId:['buy','sell','dividend','fee'].includes(form.transactionType)?(form.instrumentId||null):null,transactionType:form.transactionType,transactionDate:form.transactionDate,quantity:market?Number(form.quantity):null,price:market?Number(form.price):null,amount:amount?Number(form.amount):null,fees:['buy','sell','dividend'].includes(form.transactionType)?Number(form.fees||0):0,notes:form.notes.trim()||null};}
export function PortfolioTransactionForm({portfolio,instruments,transaction,onSubmit,loading=false}){const{t}=useTranslation();const timezone=useUserTimezone();const prefix=useId();const [form,setForm]=useState({transactionType:transaction?.transactionType||'buy',transactionDate:transaction?.transactionDate||currentDateKey(timezone),instrumentId:transaction?.instrumentId||'',quantity:String(transaction?.quantity??''),price:String(transaction?.price??''),amount:String(transaction?.amount??''),fees:String(transaction?.fees??0),notes:transaction?.notes||''});const[errors,setErrors]=useState({});const set=(key,value)=>setForm((current)=>({...current,[key]:value}));const market=useMemo(()=>['buy','sell'].includes(form.transactionType),[form.transactionType]);const needsInstrument=['buy','sell','dividend'].includes(form.transactionType);const showsInstrument=needsInstrument||form.transactionType==='fee';const hasAmount=['dividend','fee','deposit','withdrawal'].includes(form.transactionType);
  function submit(e){e.preventDefault();const next={};if(needsInstrument&&!form.instrumentId)next.instrumentId=t('portfolio.validation.instrumentRequired');if(market&&!(Number(form.quantity)>0))next.quantity=t('portfolio.validation.positive');if(market&&!(Number(form.price)>0))next.price=t('portfolio.validation.positive');if(hasAmount&&!(Number(form.amount)>0))next.amount=t('portfolio.validation.positive');setErrors(next);if(!Object.keys(next).length)onSubmit(normalizePortfolioTransaction(form,portfolio.id));}
  return <form onSubmit={submit} className="space-y-4" noValidate><div className="grid gap-4 adaptive:grid-cols-2"><Field id={`${prefix}-type`} label={t('portfolio.transactionType')} required>{(props)=><Select {...props} value={form.transactionType} onChange={(e)=>set('transactionType',e.target.value)}>{TYPES.map((type)=><option key={type} value={type}>{t(`portfolio.transactionTypes.${type}`)}</option>)}</Select>}</Field><Field id={`${prefix}-date`} label={t('common.date')} required>{(props)=><Input {...props} type="date" dir="ltr" value={form.transactionDate} onChange={(e)=>set('transactionDate',e.target.value)} />}</Field>
  {showsInstrument&&<Field id={`${prefix}-instrument`} label={t('portfolio.instrument')} required={needsInstrument} error={errors.instrumentId} helpText={form.transactionType==='fee'?t('portfolio.optionalInstrument'):undefined}>{(props)=><Select {...props} value={form.instrumentId} onChange={(e)=>set('instrumentId',e.target.value)}><option value="">{t(form.transactionType==='fee'?'portfolio.noInstrument':'portfolio.chooseInstrument')}</option>{instruments.map((item)=><option key={item.id} value={item.id}>{item.symbol} · {item.name||item.assetType}</option>)}</Select>}</Field>}
  {market&&<><Field id={`${prefix}-quantity`} label={t('common.quantity')} required error={errors.quantity}>{(props)=><Input {...props} numeric type="number" min="0" step="0.00000001" value={form.quantity} onChange={(e)=>set('quantity',e.target.value)} />}</Field><Field id={`${prefix}-price`} label={t('portfolio.price')} required error={errors.price}>{(props)=><Input {...props} numeric type="number" min="0" step="0.00000001" value={form.price} onChange={(e)=>set('price',e.target.value)} />}</Field></>}
  {hasAmount&&<Field id={`${prefix}-amount`} label={t('portfolio.amount')} required error={errors.amount}>{(props)=><Input {...props} numeric type="number" min="0" step="0.01" value={form.amount} onChange={(e)=>set('amount',e.target.value)} />}</Field>}
  {['buy','sell','dividend'].includes(form.transactionType)&&<Field id={`${prefix}-fees`} label={t('common.fees')}>{(props)=><Input {...props} numeric type="number" min="0" step="0.01" value={form.fees} onChange={(e)=>set('fees',e.target.value)} />}</Field>}</div><Field id={`${prefix}-notes`} label={t('common.notes')}><textarea id={`${prefix}-notes`} className="input min-h-20" dir="auto" value={form.notes} onChange={(e)=>set('notes',e.target.value)} /></Field><p className="text-xs text-muted">{t('portfolio.weightedAverageNotice')}</p><Button type="submit" variant="primary" size="mobile" className="w-full" disabled={loading}>{loading?t('common.saving'):t(transaction?'common.saveChanges':'portfolio.addTransaction')}</Button></form>;
}
